// ─── Synonym & Antonym Database ───────────────────────────────────────────────
// Each entry: { word, synonyms: [], antonyms: [] }
// Multiple synonyms/antonyms all accepted as correct answers

export const SYN_ANT = [
  // A
  {word:"happy",syn:["glad","joyful","pleased","content","cheerful","elated","delighted","merry","blissful","jovial"],ant:["sad","unhappy","miserable","gloomy","depressed","sorrowful","melancholy","glum","dejected","downcast"]},
  {word:"fast",syn:["quick","rapid","swift","speedy","hasty","brisk","fleet","nimble","prompt","agile"],ant:["slow","sluggish","leisurely","gradual","unhurried","plodding","dawdling","lagging","tardy","delayed"]},
  {word:"big",syn:["large","huge","vast","great","enormous","massive","gigantic","colossal","immense","substantial"],ant:["small","tiny","little","petite","minute","microscopic","miniature","compact","slight","diminutive"]},
  {word:"smart",syn:["clever","intelligent","bright","wise","sharp","astute","shrewd","brilliant","gifted","talented"],ant:["stupid","dumb","foolish","ignorant","dense","dull","obtuse","dim","slow","witless"]},
  {word:"brave",syn:["courageous","bold","fearless","daring","valiant","heroic","gallant","intrepid","audacious","dauntless"],ant:["cowardly","timid","fearful","scared","afraid","craven","spineless","faint","meek","nervous"]},
  {word:"strong",syn:["powerful","mighty","robust","sturdy","tough","muscular","forceful","potent","vigorous","firm"],ant:["weak","feeble","frail","fragile","delicate","puny","powerless","infirm","faint","helpless"]},
  {word:"beautiful",syn:["pretty","lovely","gorgeous","stunning","attractive","handsome","elegant","radiant","magnificent","exquisite"],ant:["ugly","plain","hideous","unattractive","unsightly","grotesque","repulsive","homely","ghastly","revolting"]},
  {word:"ancient",syn:["old","aged","antique","historic","archaic","venerable","timeworn","primitive","bygone","classical"],ant:["modern","new","recent","contemporary","current","fresh","novel","latest","young","newfangled"]},
  {word:"calm",syn:["peaceful","serene","tranquil","quiet","still","placid","composed","relaxed","untroubled","gentle"],ant:["agitated","anxious","turbulent","nervous","restless","frantic","hectic","frenzied","stormy","chaotic"]},
  {word:"clean",syn:["pure","spotless","immaculate","tidy","fresh","neat","sanitized","polished","sterile","hygienic"],ant:["dirty","filthy","grimy","messy","soiled","contaminated","polluted","muddy","stained","foul"]},
  {word:"cold",syn:["cool","chilly","freezing","frigid","icy","frosty","wintry","bitter","arctic","glacial"],ant:["hot","warm","burning","scorching","sweltering","blazing","boiling","heated","tropical","torrid"]},
  {word:"dark",syn:["dim","gloomy","shadowy","murky","dusky","obscure","shady","unlit","overcast","somber"],ant:["light","bright","luminous","radiant","sunny","gleaming","shining","glowing","clear","vivid"]},
  {word:"difficult",syn:["hard","tough","challenging","demanding","strenuous","arduous","complex","complicated","intricate","laborious"],ant:["easy","simple","straightforward","effortless","uncomplicated","basic","elementary","trivial","light","manageable"]},
  {word:"early",syn:["soon","prompt","timely","punctual","beforehand","ahead","premature","initial","preceding","advance"],ant:["late","overdue","delayed","tardy","behind","slow","lagging","belated","deferred","postponed"]},
  {word:"empty",syn:["bare","vacant","void","hollow","blank","barren","unfilled","deserted","abandoned","depleted"],ant:["full","filled","packed","crowded","occupied","loaded","stuffed","brimming","complete","teeming"]},
  {word:"enemy",syn:["foe","opponent","adversary","rival","antagonist","nemesis","attacker","competitor","aggressor","opposition"],ant:["friend","ally","companion","supporter","partner","colleague","associate","comrade","helper","advocate"]},
  {word:"false",syn:["untrue","wrong","incorrect","inaccurate","mistaken","erroneous","fake","bogus","deceptive","dishonest"],ant:["true","correct","accurate","right","genuine","honest","authentic","valid","real","factual"]},
  {word:"famous",syn:["well-known","celebrated","renowned","noted","prominent","distinguished","acclaimed","eminent","illustrious","legendary"],ant:["unknown","obscure","anonymous","forgotten","insignificant","unheard","nameless","invisible","ignored","overlooked"]},
  {word:"generous",syn:["giving","charitable","benevolent","kind","magnanimous","liberal","bountiful","unselfish","lavish","munificent"],ant:["selfish","greedy","stingy","miserly","cheap","mean","tight","uncharitable","inconsiderate","grasping"]},
  {word:"gentle",syn:["mild","soft","tender","kind","caring","delicate","calm","light","easy","soothing"],ant:["rough","harsh","violent","aggressive","brutal","fierce","severe","intense","rude","abrasive"]},
  {word:"honest",syn:["truthful","sincere","genuine","candid","frank","open","straightforward","trustworthy","upright","ethical"],ant:["dishonest","lying","deceitful","corrupt","fraudulent","sneaky","deceptive","false","hypocritical","untrustworthy"]},
  {word:"hot",syn:["warm","burning","scorching","blazing","boiling","sizzling","sweltering","tropical","fiery","torrid"],ant:["cold","cool","freezing","icy","frigid","chilly","frosty","arctic","bitter","wintry"]},
  {word:"humble",syn:["modest","meek","unassuming","unpretentious","low-key","reserved","quiet","simple","plain","down-to-earth"],ant:["proud","arrogant","conceited","vain","boastful","haughty","pompous","egotistical","superior","pretentious"]},
  {word:"kind",syn:["caring","compassionate","generous","warm","friendly","gentle","thoughtful","considerate","loving","charitable"],ant:["cruel","unkind","mean","harsh","callous","cold","heartless","vicious","brutal","ruthless"]},
  {word:"lazy",syn:["idle","inactive","sluggish","lethargic","indolent","slothful","listless","passive","unmotivated","inert"],ant:["hardworking","diligent","industrious","energetic","active","motivated","ambitious","productive","tireless","eager"]},
  {word:"loud",syn:["noisy","boisterous","rowdy","thunderous","deafening","blaring","raucous","shrill","clamorous","booming"],ant:["quiet","silent","soft","hushed","muffled","muted","faint","gentle","subdued","whispered"]},
  {word:"love",syn:["adore","cherish","worship","treasure","admire","care","appreciate","fancy","like","desire"],ant:["hate","despise","loathe","detest","abhor","dislike","scorn","reject","resent","disdain"]},
  {word:"lucky",syn:["fortunate","blessed","favored","charmed","prosperous","successful","advantaged","privileged","happy","auspicious"],ant:["unlucky","unfortunate","cursed","doomed","hapless","jinxed","luckless","wretched","ill-fated","miserable"]},
  {word:"new",syn:["fresh","recent","modern","current","latest","novel","original","contemporary","innovative","young"],ant:["old","ancient","aged","antique","dated","obsolete","outdated","worn","stale","archaic"]},
  {word:"noisy",syn:["loud","rowdy","boisterous","clamorous","raucous","deafening","blaring","thunderous","disruptive","turbulent"],ant:["quiet","silent","peaceful","calm","hushed","tranquil","still","noiseless","muted","serene"]},
  {word:"open",syn:["unlocked","accessible","available","exposed","uncovered","bare","clear","free","public","transparent"],ant:["closed","shut","locked","sealed","blocked","inaccessible","restricted","private","covered","concealed"]},
  {word:"perfect",syn:["flawless","ideal","excellent","supreme","faultless","impeccable","spotless","pure","optimal","outstanding"],ant:["imperfect","flawed","faulty","defective","inferior","poor","lacking","inadequate","substandard","mediocre"]},
  {word:"polite",syn:["courteous","respectful","civil","well-mannered","refined","gracious","considerate","diplomatic","tactful","cordial"],ant:["rude","impolite","disrespectful","discourteous","crude","blunt","impertinent","insolent","offensive","arrogant"]},
  {word:"poor",syn:["broke","impoverished","destitute","needy","penniless","underprivileged","struggling","bankrupt","insolvent","deprived"],ant:["rich","wealthy","affluent","prosperous","well-off","comfortable","loaded","thriving","successful","opulent"]},
  {word:"quick",syn:["fast","rapid","swift","speedy","hasty","prompt","agile","brisk","nimble","fleet"],ant:["slow","sluggish","leisurely","gradual","unhurried","tardy","plodding","lagging","delayed","lazy"]},
  {word:"quiet",syn:["silent","still","hushed","peaceful","calm","soft","gentle","muted","serene","tranquil"],ant:["loud","noisy","boisterous","rowdy","clamorous","deafening","raucous","blaring","thunderous","shrill"]},
  {word:"rich",syn:["wealthy","affluent","prosperous","well-off","loaded","opulent","thriving","comfortable","successful","moneyed"],ant:["poor","broke","impoverished","destitute","needy","penniless","bankrupt","insolvent","underprivileged","struggling"]},
  {word:"rude",syn:["impolite","disrespectful","discourteous","crude","blunt","insolent","offensive","arrogant","impertinent","boorish"],ant:["polite","courteous","respectful","civil","gracious","considerate","diplomatic","tactful","refined","mannerly"]},
  {word:"safe",syn:["secure","protected","sheltered","guarded","harmless","stable","sound","reliable","trustworthy","shielded"],ant:["dangerous","unsafe","risky","hazardous","perilous","threatening","vulnerable","exposed","unprotected","harmful"]},
  {word:"sad",syn:["unhappy","sorrowful","melancholy","gloomy","depressed","downcast","miserable","dejected","heartbroken","despondent"],ant:["happy","joyful","cheerful","elated","content","pleased","merry","blissful","delighted","glad"]},
  {word:"sharp",syn:["keen","pointed","acute","precise","clever","astute","cutting","piercing","intelligent","perceptive"],ant:["dull","blunt","stupid","obtuse","slow","dim","dense","flat","rounded","vague"]},
  {word:"shy",syn:["timid","reserved","bashful","introverted","quiet","withdrawn","modest","self-conscious","retiring","meek"],ant:["bold","confident","outgoing","extroverted","assertive","forward","brazen","audacious","sociable","brash"]},
  {word:"simple",syn:["easy","basic","elementary","plain","straightforward","uncomplicated","clear","obvious","effortless","modest"],ant:["complex","complicated","difficult","intricate","elaborate","advanced","sophisticated","convoluted","challenging","ornate"]},
  {word:"slow",syn:["sluggish","leisurely","gradual","unhurried","plodding","lagging","tardy","dawdling","deliberate","measured"],ant:["fast","quick","rapid","swift","speedy","hasty","brisk","fleet","nimble","prompt"]},
  {word:"smart",syn:["clever","intelligent","bright","wise","sharp","astute","shrewd","brilliant","gifted","talented"],ant:["stupid","dumb","foolish","ignorant","dense","dull","obtuse","dim","slow","witless"]},
  {word:"tall",syn:["high","towering","lofty","elevated","soaring","imposing","grand","statuesque","lengthy","lanky"],ant:["short","small","tiny","low","squat","petite","compact","diminutive","stubby","stumpy"]},
  {word:"thin",syn:["slim","slender","lean","narrow","slight","svelte","skinny","gaunt","wiry","spare"],ant:["fat","thick","wide","broad","heavy","large","bulky","stout","plump","obese"]},
  {word:"tired",syn:["exhausted","weary","fatigued","drained","sleepy","worn","drowsy","spent","lethargic","depleted"],ant:["energetic","rested","refreshed","alert","vigorous","lively","active","awake","fresh","invigorated"]},
  {word:"ugly",syn:["unattractive","plain","hideous","unsightly","grotesque","repulsive","homely","ghastly","revolting","unpleasant"],ant:["beautiful","pretty","lovely","gorgeous","stunning","attractive","handsome","elegant","radiant","magnificent"]},
  {word:"weak",syn:["feeble","frail","fragile","delicate","puny","powerless","infirm","faint","helpless","ineffective"],ant:["strong","powerful","mighty","robust","sturdy","tough","muscular","forceful","potent","vigorous"]},
  {word:"wide",syn:["broad","expansive","vast","spacious","extensive","open","large","ample","sweeping","generous"],ant:["narrow","thin","slim","tight","confined","restricted","limited","compact","slender","slight"]},
  {word:"wise",syn:["intelligent","clever","smart","knowledgeable","informed","experienced","sage","astute","insightful","discerning"],ant:["foolish","stupid","ignorant","naive","unwise","reckless","senseless","irrational","shortsighted","imprudent"]},
  {word:"young",syn:["youthful","juvenile","new","fresh","immature","adolescent","early","budding","nascent","developing"],ant:["old","aged","elderly","ancient","mature","senior","veteran","experienced","seasoned","withered"]},
  // More
  {word:"accept",syn:["receive","take","approve","embrace","welcome","adopt","acknowledge","agree","recognize","permit"],ant:["reject","refuse","deny","decline","dismiss","oppose","resist","repudiate","rebuff","exclude"]},
  {word:"add",syn:["include","append","attach","combine","join","supplement","increase","extend","insert","incorporate"],ant:["subtract","remove","reduce","eliminate","delete","deduct","exclude","separate","diminish","withdraw"]},
  {word:"allow",syn:["permit","let","authorize","approve","grant","enable","sanction","tolerate","accept","endorse"],ant:["forbid","prohibit","deny","prevent","block","restrict","ban","refuse","oppose","hinder"]},
  {word:"attack",syn:["assault","strike","charge","invade","raid","ambush","assail","bombard","besiege","rush"],ant:["defend","protect","guard","shield","retreat","withdraw","flee","surrender","yield","escape"]},
  {word:"begin",syn:["start","commence","initiate","launch","open","introduce","originate","establish","create","found"],ant:["end","finish","stop","conclude","terminate","complete","cease","halt","abandon","quit"]},
  {word:"buy",syn:["purchase","acquire","obtain","get","procure","invest","secure","pay","trade","shop"],ant:["sell","trade","auction","vend","market","retail","liquidate","dispose","offload","distribute"]},
  {word:"cheap",syn:["inexpensive","affordable","budget","economical","low-cost","reasonable","modest","discounted","bargain","thrifty"],ant:["expensive","costly","pricey","dear","premium","luxury","extravagant","lavish","steep","overpriced"]},
  {word:"connect",syn:["join","link","unite","attach","tie","bond","merge","combine","bridge","integrate"],ant:["disconnect","separate","divide","detach","sever","split","isolate","break","cut","untie"]},
  {word:"create",syn:["make","build","produce","design","construct","develop","invent","form","craft","generate"],ant:["destroy","demolish","ruin","wreck","break","dismantle","eliminate","erase","abolish","negate"]},
  {word:"cry",syn:["weep","sob","wail","whimper","bawl","mourn","grieve","lament","snivel","howl"],ant:["laugh","smile","chuckle","giggle","grin","beam","rejoice","celebrate","delight","cheer"]},
  {word:"dangerous",syn:["risky","hazardous","perilous","threatening","unsafe","harmful","menacing","treacherous","precarious","deadly"],ant:["safe","secure","protected","harmless","stable","reliable","sound","sheltered","guarded","benign"]},
  {word:"destroy",syn:["demolish","ruin","wreck","shatter","annihilate","obliterate","eradicate","devastate","dismantle","eliminate"],ant:["create","build","construct","make","repair","restore","fix","preserve","protect","maintain"]},
  {word:"dream",syn:["imagine","fantasize","envision","aspire","wish","hope","contemplate","visualize","desire","long"],ant:["reality","fact","truth","actuality","certainty","concreteness","pragmatism","realism","practicality","logic"]},
  {word:"expand",syn:["grow","increase","enlarge","extend","widen","broaden","amplify","develop","spread","magnify"],ant:["shrink","reduce","decrease","contract","narrow","compress","limit","minimize","diminish","constrict"]},
  {word:"fail",syn:["lose","flop","miss","struggle","underperform","stumble","collapse","bomb","falter","blunder"],ant:["succeed","win","achieve","accomplish","triumph","excel","prevail","conquer","thrive","prosper"]},
  {word:"find",syn:["discover","locate","uncover","detect","identify","spot","encounter","retrieve","obtain","track"],ant:["lose","misplace","miss","overlook","hide","conceal","discard","abandon","drop","forget"]},
  {word:"fix",syn:["repair","mend","restore","correct","solve","patch","heal","rectify","improve","adjust"],ant:["break","damage","ruin","destroy","worsen","harm","shatter","impair","sabotage","wreck"]},
  {word:"forgive",syn:["pardon","excuse","absolve","overlook","condone","spare","release","acquit","exonerate","reconcile"],ant:["blame","accuse","punish","condemn","resent","hold","prosecute","indict","convict","sentence"]},
  {word:"free",syn:["liberate","release","unlock","unchain","emancipate","rescue","loose","untie","deliver","spare"],ant:["imprison","confine","restrict","trap","chain","bind","limit","capture","contain","lock"]},
  {word:"give",syn:["donate","offer","provide","grant","bestow","present","share","contribute","supply","hand"],ant:["take","receive","keep","withhold","steal","grab","seize","retain","hoard","refuse"]},
  {word:"grow",syn:["expand","increase","develop","mature","flourish","thrive","progress","advance","multiply","bloom"],ant:["shrink","decline","decrease","wither","die","fail","stagnate","deteriorate","fade","diminish"]},
  {word:"hide",syn:["conceal","cover","disguise","mask","camouflage","bury","shelter","tuck","screen","veil"],ant:["reveal","show","expose","display","uncover","disclose","exhibit","present","demonstrate","unveil"]},
  {word:"increase",syn:["grow","expand","rise","boost","enhance","elevate","multiply","amplify","escalate","augment"],ant:["decrease","reduce","lower","cut","shrink","diminish","decline","drop","lessen","minimize"]},
  {word:"join",syn:["connect","link","unite","merge","combine","attach","associate","collaborate","participate","integrate"],ant:["leave","separate","divide","quit","abandon","disconnect","split","detach","withdraw","depart"]},
  {word:"keep",syn:["retain","hold","maintain","preserve","store","save","guard","protect","sustain","continue"],ant:["lose","discard","release","abandon","surrender","give","drop","reject","dispose","relinquish"]},
  {word:"leave",syn:["depart","go","exit","abandon","vacate","escape","flee","withdraw","quit","desert"],ant:["stay","remain","arrive","come","return","enter","join","settle","continue","persist"]},
  {word:"like",syn:["enjoy","love","appreciate","admire","prefer","favor","cherish","relish","fancy","adore"],ant:["dislike","hate","despise","detest","loathe","abhor","oppose","reject","resent","avoid"]},
  {word:"lose",syn:["misplace","fail","forfeit","surrender","drop","miss","squander","waste","suffer","yield"],ant:["win","find","gain","succeed","keep","achieve","obtain","retrieve","triumph","prosper"]},
  {word:"mend",syn:["fix","repair","restore","heal","patch","correct","improve","recover","rehabilitate","renew"],ant:["break","damage","ruin","destroy","harm","shatter","tear","impair","crack","wreck"]},
  {word:"move",syn:["go","travel","shift","transfer","carry","transport","relocate","migrate","advance","proceed"],ant:["stay","stop","halt","remain","freeze","rest","pause","linger","idle","stagnate"]},
  {word:"narrow",syn:["thin","slim","confined","tight","restricted","limited","compact","slender","close","constricted"],ant:["wide","broad","expansive","vast","spacious","large","open","ample","generous","sweeping"]},
  {word:"obey",syn:["follow","comply","submit","adhere","conform","respect","observe","fulfill","execute","yield"],ant:["disobey","defy","rebel","resist","refuse","violate","ignore","break","challenge","oppose"]},
  {word:"protect",syn:["guard","defend","shield","preserve","secure","shelter","safeguard","cover","watch","maintain"],ant:["expose","attack","harm","endanger","threaten","abandon","neglect","weaken","damage","destroy"]},
  {word:"push",syn:["shove","press","thrust","drive","propel","force","nudge","prod","urge","advance"],ant:["pull","drag","draw","attract","invite","lure","entice","coax","beckon","invite"]},
  {word:"remember",syn:["recall","recollect","retain","recognize","memorize","think","review","revisit","reminisce","reflect"],ant:["forget","overlook","ignore","neglect","miss","lose","blank","disregard","dismiss","omit"]},
  {word:"rough",syn:["bumpy","coarse","jagged","uneven","rugged","harsh","abrasive","scratchy","choppy","turbulent"],ant:["smooth","soft","flat","even","polished","sleek","silky","gentle","calm","refined"]},
  {word:"save",syn:["rescue","preserve","protect","keep","retain","store","economize","conserve","recover","spare"],ant:["waste","spend","lose","destroy","abandon","squander","discard","exhaust","consume","ruin"]},
  {word:"serious",syn:["earnest","solemn","grave","important","significant","urgent","severe","critical","intense","focused"],ant:["silly","trivial","funny","playful","lighthearted","unimportant","casual","frivolous","comic","flippant"]},
  {word:"share",syn:["divide","split","distribute","give","contribute","offer","provide","exchange","communicate","spread"],ant:["keep","hoard","withhold","hide","conceal","monopolize","retain","exclude","restrict","refuse"]},
  {word:"shrink",syn:["reduce","decrease","contract","compress","narrow","minimize","diminish","lessen","deflate","condense"],ant:["expand","grow","increase","enlarge","extend","widen","amplify","balloon","swell","magnify"]},
  {word:"speak",syn:["talk","say","tell","communicate","express","utter","voice","announce","articulate","declare"],ant:["listen","silence","hush","quiet","mute","suppress","withhold","hide","conceal","ignore"]},
  {word:"start",syn:["begin","launch","initiate","open","commence","create","found","introduce","establish","trigger"],ant:["end","finish","stop","conclude","terminate","quit","abandon","cease","halt","close"]},
  {word:"stay",syn:["remain","linger","continue","persist","wait","abide","dwell","reside","settle","endure"],ant:["leave","go","depart","exit","flee","escape","abandon","vacate","withdraw","quit"]},
  {word:"stop",syn:["halt","cease","end","quit","pause","conclude","finish","terminate","abandon","discontinue"],ant:["start","begin","continue","proceed","advance","go","persist","carry","maintain","resume"]},
  {word:"succeed",syn:["win","achieve","accomplish","triumph","excel","prevail","conquer","flourish","thrive","prosper"],ant:["fail","lose","struggle","flop","miss","stumble","collapse","falter","blunder","underperform"]},
  {word:"take",syn:["grab","seize","capture","obtain","receive","acquire","collect","claim","accept","steal"],ant:["give","offer","provide","donate","return","restore","contribute","surrender","release","relinquish"]},
  {word:"teach",syn:["educate","instruct","train","guide","tutor","coach","mentor","inform","explain","demonstrate"],ant:["learn","study","ignore","mislead","confuse","deceive","withhold","hide","conceal","obfuscate"]},
  {word:"thick",syn:["dense","heavy","solid","fat","wide","broad","bulky","stout","massive","chunky"],ant:["thin","slim","slender","narrow","light","delicate","slight","lean","sparse","wispy"]},
  {word:"trust",syn:["believe","rely","depend","faith","confidence","accept","assume","credit","count","support"],ant:["doubt","distrust","suspect","question","disbelieve","challenge","oppose","contest","mistrust","deny"]},
  {word:"ugly",syn:["unattractive","hideous","unsightly","plain","grotesque","homely","repulsive","ghastly","revolting","offensive"],ant:["beautiful","pretty","lovely","gorgeous","stunning","attractive","handsome","elegant","radiant","exquisite"]},
  {word:"understand",syn:["comprehend","grasp","know","realize","recognize","perceive","follow","appreciate","learn","master"],ant:["misunderstand","confuse","ignore","overlook","miss","forget","misjudge","misconceive","mistake","misread"]},
  {word:"unite",syn:["join","merge","combine","connect","link","bond","integrate","collaborate","associate","cooperate"],ant:["divide","separate","split","break","isolate","disconnect","oppose","sever","alienate","segregate"]},
  {word:"use",syn:["employ","apply","utilize","operate","exercise","practice","work","exploit","handle","engage"],ant:["waste","misuse","ignore","avoid","discard","neglect","abandon","refuse","reject","forego"]},
  {word:"win",syn:["succeed","triumph","achieve","conquer","prevail","earn","gain","capture","excel","dominate"],ant:["lose","fail","surrender","yield","forfeit","concede","drop","fall","struggle","underperform"]},
  {word:"work",syn:["labor","toil","operate","function","perform","produce","accomplish","strive","effort","serve"],ant:["rest","relax","play","idle","lounge","stop","fail","break","quit","pause"]},
  {word:"worry",syn:["stress","fear","dread","fret","anxiety","concern","trouble","unease","apprehension","panic"],ant:["calm","relax","trust","confidence","peace","ease","comfort","assurance","serenity","security"]},
];

// Index by word for fast lookup
export const SYN_ANT_MAP = Object.fromEntries(SYN_ANT.map(e => [e.word, e]));

// Just synonyms list (for Synonyms game)
export const SYNONYMS_ONLY = SYN_ANT.filter(e => e.syn.length > 0);

// Just antonyms list (for Antonyms game)
export const ANTONYMS_ONLY = SYN_ANT.filter(e => e.ant.length > 0);

export default { SYN_ANT, SYN_ANT_MAP, SYNONYMS_ONLY, ANTONYMS_ONLY };
