// AccuratKey game constants — separate file to avoid webpack TDZ

export const LEVELS = [
  { id:1,  name:"Home Row Hero",         emoji:"🏠", wpmTarget:12,  accuracy:75, color:"#10b981", words:["ffjj","fjfj","asdf","jkl;","add","ask","fall","glad","flask","lads","fads","salads"] },
  { id:2,  name:"Top Row Climber",       emoji:"🧗", wpmTarget:16,  accuracy:75, color:"#3b82f6", words:["quit","wrap","type","your","power","tower","write","pretty","quite","report"] },
  { id:3,  name:"Full Board Basics",     emoji:"⌨️", wpmTarget:20,  accuracy:75, color:"#8b5cf6", words:["the","and","for","you","big","hot","map","key","ask","say","put","old","new","see","try","own","two","way","how","run"] },
  { id:4,  name:"Word Builder",          emoji:"🔨", wpmTarget:25,  accuracy:75, color:"#f59e0b", words:["water","every","first","place","years","young","great","three","never","world","about","right","could","still","small","found"] },
  { id:5,  name:"Speed Seeker",          emoji:"🚀", wpmTarget:30,  accuracy:75, color:"#ef4444", words:["people","before","should","between","through","because","without","another","against","thought","looking","children","problem","school"] },
  { id:6,  name:"Rhythm Rider",          emoji:"🎵", wpmTarget:35,  accuracy:75, color:"#06b6d4", words:["practice","keyboard","fingers","accuracy","improve","typing","computer","program","achieve","success","quickly","journey","forward","perfect"] },
  { id:7,  name:"Flow State",            emoji:"🌊", wpmTarget:40,  accuracy:75, color:"#ec4899", words:["development","environment","technology","information","understand","experience","important","following","sometimes","something","everything","different"] },
  { id:8,  name:"Steady Hands",          emoji:"🎯", wpmTarget:45,  accuracy:75, color:"#f97316", words:["communication","international","organization","understanding","professional","relationship","immediately","particularly","responsibility","approximately"] },
  { id:9,  name:"The Zone",              emoji:"⚡", wpmTarget:50,  accuracy:75, color:"#a855f7", words:["implementation","administration","circumstances","representative","accomplishment","infrastructure","simultaneously","recommendations","acknowledgment"] },
  { id:10, name:"Turbo Typist",          emoji:"🔥", wpmTarget:55,  accuracy:75, color:"#ef4444", words:["thequickbrownfox","shesellsseashells","howmuchwoodcould","packmyboxwithfive","thefiveboxingwizards","jackdawslovemybig","fixingquartz","jumpingquickly","waxyourfivezinc"] },
  { id:11, name:"Precision Pro",         emoji:"💎", wpmTarget:60,  accuracy:75, color:"#6366f1", words:["extraordinary","indistinguishable","miscommunication","uncharacteristically","counterproductive","straightforwardness","unpredictability","incomprehensible","unconventionally","disproportionate","acknowledgement","characteristically","instantaneously"] },
  { id:12, name:"Key Wizard",            emoji:"🧙", wpmTarget:65,  accuracy:75, color:"#8b5cf6", words:["practiceisthekeytomastery","focusonaccuracybeforespeed","typingisaskillbuiltovertime","keepyoureyesonthescreen","smoothrhythmbeatsbursttyping","thequickbrownfoxjumpedoverthedog","alwaysreturntohomerow"] },
  { id:13, name:"Lightning Fingers",     emoji:"⚡", wpmTarget:70,  accuracy:75, color:"#facc15", words:["weholdthesetruthstobeselfevident","inthemiddleofeverydifficultyliesopportunity","successisnotfinalfailureisnotfatal","youmissonehandredpercentoftheshotsyoudontake","thebesttimetoplantatreewastwentyyearsago"] },
  { id:14, name:"Speed Demon",           emoji:"👹", wpmTarget:80,  accuracy:75, color:"#f43f5e", words:["tobeornottobethatisthequestion","allthatglittersisnotgold","thereisnothingeithergoodorbadbutthinkingmakesitso","itwasabrightcoldday","thecourseoftrueloveneverranunsmoothly"] },
  { id:15, name:"Legend",                emoji:"🏆", wpmTarget:90,  accuracy:75, color:"#fbbf24", words:["itwasthebestoftimesitwastheworstoftimes","asknotwhatyourcountrycandoforyouaskwhatyoucandoforyourcountry","fourscoreandsevenyearsagoourforefathersbroughtforthuponthiscontinent","onesmallstepformanonegiantleapformankind","donotgogentleintothatgoodnightrageinagethedyingofthelight"] },

  // ── NEW LEVELS 16-65 ─────────────────────────────────────────────────────────

  // Common words sprint
  { id:16, name:"Word Sprint",           emoji:"🏃", wpmTarget:35,  accuracy:75, color:"#22c55e", words:["time","person","year","way","day","thing","man","world","life","hand","part","place","case","week","company","system","program","question","government","number","night","point","home","water","room","mother","area","money","story","fact","month","lot","right","study","book","eye","job","word","business","issue","side","kind","head","house","service","friend","father","power","hour","game","line","end","among","while","name","land","large","soon","big","next","early","young","important","public","private","real","best","free","only","old","high","order","local","current","national","education","health","social","economic","political","legal","medical","financial","cultural","environmental","international","technological","scientific","historical"] },

  // Coding keywords
  { id:17, name:"Tech Talk",             emoji:"💻", wpmTarget:38,  accuracy:75, color:"#34d399", words:["function","return","const","let","var","if","else","for","while","class","import","export","async","await","try","catch","throw","new","this","true","false","null","undefined","typeof","instanceof","switch","case","break","continue","default","delete","void","yield","static","super","extends","implements","interface","package","private","protected","public","abstract","final","synchronized","volatile","transient","native","strictfp","assert","enum"] },

  // Tongue twisters (no spaces)
  { id:18, name:"Twist It",              emoji:"🌀", wpmTarget:40,  accuracy:75, color:"#f472b6", words:["shesellsseashellsbytheseashore","peterpiperpckedapeckofpickledpeppers","howmuchwoodwouldawoodchuckchuck","bettyboterboterbutterbutterisbitter","sixslipperysnailsslidslowly","redlorryyellowlorry","uniquenewyork","toyboatoyboat","thirtythreethiefsthoughtthings","blackbackbatbag","sixthickthisletssticks","rubberbabybuggybumpers"] },

  // Famous quotes no spaces
  { id:19, name:"Quote Runner",          emoji:"📖", wpmTarget:42,  accuracy:75, color:"#818cf8", words:["bethechangeyouwishtoSeeintheworld","theonlywaytodomadworkistolovewhatyoudo","imaginationismoreimportantthanknoWledge","lifeiswhatyoumakeit","thejourneYofathousandmilesbeginswithonestep","intheenditsnottheyearsinyourlifethatcountitsthelifeinyouryears","successisnotthekeytoHappiness","wherethereisnowillthereisaway","thebesttimetostartissecondbesttimenow"] },

  // Numbers and symbols adjacent to letters
  { id:20, name:"Number Words",          emoji:"🔢", wpmTarget:35,  accuracy:75, color:"#fb923c", words:["one","two","three","four","five","six","seven","eight","nine","ten","eleven","twelve","thirteen","fourteen","fifteen","sixteen","seventeen","eighteen","nineteen","twenty","thirty","forty","fifty","sixty","seventy","eighty","ninety","hundred","thousand","million","billion","trillion","first","second","third","fourth","fifth","sixth","seventh","eighth","ninth","tenth"] },

  // Animals
  { id:21, name:"Wild Words",            emoji:"🦊", wpmTarget:38,  accuracy:75, color:"#fbbf24", words:["elephant","rhinoceros","hippopotamus","chimpanzee","orangutan","crocodile","alligator","salamander","chameleon","porcupine","wolverine","armadillo","capybara","platypus","narwhal","flamingo","pelican","penguin","albatross","chameleon","komododragon","tarantula","scorpion","centipede","millipede","butterfly","dragonfly","hummingbird","woodpecker","roadrunner"] },

  // Geography
  { id:22, name:"Around the World",      emoji:"🌏", wpmTarget:40,  accuracy:75, color:"#2dd4bf", words:["Afghanistan","Bangladesh","Cameroon","Denmark","Ethiopia","Finlnad","Guatemala","Honduras","Indonesia","Jamaica","Kazakhstan","Lebanon","Madagascar","Namibia","Oman","Pakistan","Qatar","Romania","Singapore","Tanzania","Uruguay","Venezuela","Uzbekistan","Zimbabwe","Philippines","Switzerland","Netherlands","Azerbaijan","Mozambique","Kyrgyzstan"] },

  // Science words
  { id:23, name:"Science Lab",           emoji:"🔬", wpmTarget:42,  accuracy:75, color:"#38bdf8", words:["photosynthesis","mitochondria","chromosome","deoxyribonucleic","electromagnetic","thermodynamics","spectroscopy","chromatography","electrochemistry","astrophysics","neuroscience","biochemistry","paleontology","oceanography","meteorology","seismology","crystallography","nanotechnology","biotechnology","epidemiology","pharmacology","toxicology","immunology","bacteriology","virology","parasitology","genetics","genomics","proteomics","metabolomics"] },

  // Music related
  { id:24, name:"Music Words",           emoji:"🎵", wpmTarget:38,  accuracy:75, color:"#e879f9", words:["symphony","orchestra","instrument","melody","harmony","rhythm","tempo","dynamics","crescendo","diminuendo","fortissimo","pianissimo","allegretto","moderato","andante","accelerando","ritardando","syncopation","counterpoint","polyphony","monophony","heterophony","timbre","resonance","vibrato","tremolo","staccato","legato","pizzicato","arpeggiate"] },

  // Food names
  { id:25, name:"Food Run",              emoji:"🍕", wpmTarget:35,  accuracy:75, color:"#f97316", words:["spaghetti","carbonara","guacamole","quesadilla","enchilada","bruschetta","capricciosa","margherita","bolognese","fettuccine","prosciutto","mozzarella","parmesan","gorgonzola","mascarpone","tiramisu","cannoli","biscotti","panzanella","gazpacho","ratatouille","bouillabaisse","croissant","brioche","baguette","profiterole","macaroon","creme brulee","chateaubriand","bourgignon"] },

  // Alternating hands (ergonomic)
  { id:26, name:"Both Hands",            emoji:"🤲", wpmTarget:45,  accuracy:75, color:"#84cc16", words:["element","problem","visible","formula","bicycle","suspend","neurotic","penalty","stomach","blanket","captain","diagram","edition","fiction","general","hundred","journey","kingdom","laundry","maximum","nominal","optical","pattern","quality","railway","several","texture","unusual","vitamin","warning","exactly","factory","gallons","hundred","islands","jasmine","kitchen","lending","morning","nothing","opening","quickly","reading","setting","turning","uniform","village","western","younger"] },

  // Long compound words
  { id:27, name:"Long Words",            emoji:"📏", wpmTarget:48,  accuracy:75, color:"#a78bfa", words:["groundbreaking","overwhelming","understanding","uncomfortable","internationally","misrepresentation","straightforward","underestimated","overcomplicating","misunderstanding","underperforming","overachievement","counterintuitive","underdeveloped","interconnected","multidimensional","self-sufficient","extraordinarily","unenthusiastically","hypersensitivity","underappreciated","overprotective","misinterpreting","hyperventilating","uncharacteristic","unprofessional","disenfranchised","unconstitutional","insubordination","electromagnetic"] },

  // Short fast words
  { id:28, name:"Short Burst",           emoji:"💨", wpmTarget:55,  accuracy:75, color:"#f43f5e", words:["the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just","him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","us"] },

  // Programming patterns
  { id:29, name:"Code Words",            emoji:"🖥️", wpmTarget:50,  accuracy:75, color:"#06b6d4", words:["functioncallback","returnpromise","asyncfunction","awaitfetch","trycatchfinally","constresult","letcounter","varlegacy","classcomponent","importreact","exportdefault","usestatehook","useeffecthook","arraymap","arrayfilter","arrayreduce","objectkeys","objectvalues","objectentries","jsonparse","jsonstringify","consolelog","consoleerror","documentquery","eventlistener","setinterval","settimeout","requestanimation","localstorageget","localstorageset"] },

  // Classic literature phrases (no spaces)
  { id:30, name:"Classic Lines",         emoji:"📚", wpmTarget:52,  accuracy:75, color:"#c084fc", words:["tobeornottobethatisthequestion","callmoishmael","itwasthebestoftimes","itisatruthuniversallyacknowledged","inthebeginningwastheword","onceupona timeinafarawayland","theonlywaytodogreatworkistoloveit","stayhungrystayfoolish","aneyeforaneyemakesthewholeworldblind","thejourneyofathousandmiles","weholdthesetruthstobeselfevident","fourscoreandsevenyearsago","asknotwhatyourcountrycan","spacethefinalfrontier","maytheforcebewithyou","elementarymydearwatson","franklydarlinidontgiveadamn","hereislookingatyoukid"] },

  // Medical terms
  { id:31, name:"Medical Terms",         emoji:"🩺", wpmTarget:50,  accuracy:75, color:"#34d399", words:["cardiovascular","hypertension","hyperlipidemia","atherosclerosis","arrhythmia","tachycardia","bradycardia","electrocardiogram","echocardiogram","angioplasty","appendicitis","cholecystitis","pancreatitis","gastroenteritis","nephrology","urology","neurology","ophthalmology","otolaryngology","rheumatology","endocrinology","hematology","oncology","pulmonology","dermatology","psychiatry","orthopedics","anesthesiology","radiology","pathology"] },

  // Sports
  { id:32, name:"Sports Words",          emoji:"⚽", wpmTarget:42,  accuracy:75, color:"#facc15", words:["touchdown","quarterback","linebacker","cornerback","defenseman","goalkeeper","midfielder","centerfield","shortstop","tournament","championship","semifinal","quarterfinal","elimination","qualification","substitution","penalty","offside","freeThrow","threepointline","powerplay","breakaway","fastbreak","alleyoop","slapshot","golfcourse","marathon","triathlon","decathlon","heptathlon"] },

  // Weather and nature
  { id:33, name:"Nature Words",          emoji:"🌿", wpmTarget:40,  accuracy:75, color:"#86efac", words:["thunderstorm","precipitation","evaporation","condensation","atmospheric","stratosphere","troposphere","mesosphere","thermosphere","magnetosphere","biodiversity","ecosystem","photosynthesis","decomposition","nitrogen","phosphorus","potassium","chlorophyll","mitochondria","chloroplast","metamorphosis","pollination","germination","deforestation","reforestation","conservation","sustainability","renewable","nonrenewable","hydroelectric"] },

  // Business jargon
  { id:34, name:"Business Words",        emoji:"💼", wpmTarget:48,  accuracy:75, color:"#94a3b8", words:["synergy","leverage","paradigm","scalable","disruption","bandwidth","stakeholder","deliverable","milestone","roadmap","iteration","agile","scrum","kanban","backlog","sprint","retrospective","onboarding","offboarding","performance","metrics","analytics","dashboard","pipeline","conversion","acquisition","retention","churnrate","engagement","monetization"] },

  // Mythology
  { id:35, name:"Mythology",             emoji:"🏛️", wpmTarget:45,  accuracy:75, color:"#fbbf24", words:["Prometheus","Persephone","Demeter","Hephaestus","Dionysus","Aphrodite","Poseidon","Artemis","Athena","Hermes","Odysseus","Achilles","Agamemnon","Patroclus","Penelope","Telemachus","Polyphemus","Calypso","Circe","Tiresias","Narcissus","Orpheus","Eurydice","Theseus","Ariadne","Minotaur","Andromeda","Perseus","Medusa","Bellerophon"] },

  // Alliterations
  { id:36, name:"Alliterations",         emoji:"🔤", wpmTarget:50,  accuracy:75, color:"#f472b6", words:["peterpiperpicked","sallysellsseashells","bigblackbugbled","seventhsleepysheep","smoothsnakeslid","sixslimyslugs","proudprancingpony","cleancleverclaws","dancing daffodils daily","fredforgotfifty","gracefulgreengecko","harvesthappyhens","ipicked icy igloos","junglejaguarjumped","kinkykrakenknocked","largelazylobsters","mintymorningmist","nicenauticalnight"] },

  // Rhyming words
  { id:37, name:"Rhyming Words",         emoji:"🎤", wpmTarget:45,  accuracy:75, color:"#fb923c", words:["lightnight","bringspring","thingring","playday","makebreak","fightmight","roundsound","loveabove","findkind","mindwind","growshow","knowflow","throwbelow","standhand","movelove","learnburn","highsky","tryfry","stayplay","waymay","beengreen","seenclean","donegone","sunfun","rungun","cometome","homeroam","timerime","dreamstream","heartstart"] },

  // Motivational phrases
  { id:38, name:"Power Phrases",         emoji:"💪", wpmTarget:55,  accuracy:75, color:"#ef4444", words:["believeinyourself","nevergiveuP","hardworkpaysoff","dreambigworkhardstayhumble","successisajourney","pushingyourlimits","beyondyourcomfortzone","disciplinebeatstalent","consistencyiskey","focusonprogress","onedayatatime","makeithappen","keepmovingforward","riseandgrind","noshortscuts","embracethegrind","stayhungry","keepgoing","beunstoppable","dominate"] },

  // Countries capitals
  { id:39, name:"World Capitals",        emoji:"🗺️", wpmTarget:42,  accuracy:75, color:"#38bdf8", words:["Canberra","Brasilia","Ottawa","Beijing","Bogota","Havana","Prague","Copenhagen","Cairo","Helsinki","Budapest","Reykjavik","Jakarta","Tehran","Baghdad","Dublin","Jerusalem","Tokyo","Amman","Nairobi","Pyongyang","Seoul","Beirut","Vilnius","Luxembourg","Skopje","Kuala","Valletta","Wellington","Kathmandu","Amsterdam","Islamabad","Manila","Warsaw","Lisbon","Bucharest","Moscow","Riyadh","Belgrade","Bratislava","Ljubljana","Mogadishu","Pretoria","Madrid","Khartoum","Stockholm","Bern","Damascus","Taipei","Ankara","Kyiv","Montevideo","Tashkent","Caracas","Hanoi","Sana"] },

  // Tech company names & products
  { id:40, name:"Tech Terms",            emoji:"🏢", wpmTarget:50,  accuracy:75, color:"#818cf8", words:["cryptocurrency","blockchain","distributed","decentralized","machinelearning","artificialintelligence","deeplearning","neuralnetwork","algorithm","optimization","virtualization","containerization","microservices","kubernetes","orchestration","serverless","cloudcomputing","devops","devsecops","infrastructure","automation","monitoring","observability","telemetry","latency","throughput","scalability","redundancy","failover","loadbalancing"] },

  // Homophones
  { id:41, name:"Homophones",            emoji:"👂", wpmTarget:45,  accuracy:75, color:"#a3e635", words:["their","there","they're","your","you're","its","it's","whose","who's","affect","effect","accept","except","lay","lie","raise","rise","fewer","less","further","farther","principal","principle","stationary","stationery","complement","compliment","elicit","illicit","eminent","imminent","averse","adverse","assure","ensure","insure","council","counsel","allude","elude","allusion","illusion","cite","sight","site","to","too","two","bare","bear","buy","by","bye"] },

  // Compound words
  { id:42, name:"Compound Words",        emoji:"🔗", wpmTarget:48,  accuracy:75, color:"#e2e8f0", words:["sunflower","moonlight","starfish","thunderstorm","rainbow","waterfall","fireplace","snowflake","earthquake","whirlpool","butterscotch","grasshopper","dragonfly","bullseye","honeybee","toadstool","nightfall","daybreak","footprint","handshake","heartbeat","brainwave","lifeguard","bookworm","daydream","moonwalk","sunburn","windmill","driftwood","clockwork"] },

  // Adverbs
  { id:43, name:"Adverbs",               emoji:"✨", wpmTarget:50,  accuracy:75, color:"#67e8f9", words:["absolutely","accidentally","actually","already","always","approximately","basically","carefully","certainly","clearly","completely","constantly","correctly","currently","definitely","deliberately","directly","easily","efficiently","entirely","especially","eventually","exactly","extremely","finally","fortunately","frequently","generally","gradually","honestly","immediately","importantly","incredibly","inevitably","innocently","intentionally","largely","literally","logically","mainly","meanwhile","mentally","naturally","nearly","necessarily","obviously","partially","particularly","perfectly","physically","possibly","practically","precisely","previously","probably","quickly","quietly","rapidly","really","recently","regularly","relatively","remarkably","repeatedly","seriously","significantly","simply","slightly","slowly","specifically","strongly","successfully","suddenly","supposedly","surprisingly","typically","unfortunately","usually","virtually","vividly","willingly","wonderfully"] },

  // Prefixes practice
  { id:44, name:"Prefixes",              emoji:"🔑", wpmTarget:52,  accuracy:75, color:"#c4b5fd", words:["predetermined","preposterous","prerequisite","premonition","prehistoric","predominant","preliminary","precautionary","pronunciation","precipitation","preparation","presentation","preservation","presumptuous","preternatural","supernatural","superimposed","superconductor","superstitious","superficial","superfluous","superlative","supremacy","surpassing","surrounding","survival","sustainable","systematic","syndication","symptomatic"] },

  // Emoji descriptions (no emoji, just the words)
  { id:45, name:"Descriptive Words",     emoji:"🖊️", wpmTarget:48,  accuracy:75, color:"#fde68a", words:["rollinglaughing","facewithtearsof","starstruckeyes","thinkingface","explodinghead","mindblown","hearteyesface","sunglassescool","upsetface","sleepingface","grimacingface","hushedface","fearfulface","worriedface","confusedface","flushedface","perseveringface","disappointedface","anguishedface","fearstruckeyes","coldsweatface","openmouth","astonishedface","wearyface","tiredness","sleepiness","screamingfear","confoundedface","poutingface","angryface"] },

  // Spelling bee words
  { id:46, name:"Hard Spellings",        emoji:"🐝", wpmTarget:55,  accuracy:75, color:"#fcd34d", words:["pneumonia","mnemonic","acquiesce","cacophony","egregious","ephemeral","perfidious","sycophant","ubiquitous","verisimilitude","perspicacious","loquacious","magnanimous","ostentatious","mellifluous","obsequious","parsimonious","querulous","recalcitrant","solipsistic","tenacious","undulating","vivacious","zealous","abstemious","bellicose","cantankerous","dilettante","effervescent","fastidious","garrulous","histrionic","impecunious","jejune","knavish","lugubrious"] },

  // Historical figures (lowercase no spaces)
  { id:47, name:"Famous Names",          emoji:"🏺", wpmTarget:50,  accuracy:75, color:"#d97706", words:["napoleon","cleopatra","charlemagne","genghiskhan","alexanderthegreat","juliuscaesar","marcoantony","marcopolo","christophercolumbus","leonardodavinci","michelangelo","galileogalilei","isaacnewton","benjaminfranklin","georgewashington","abrahamlincoln","theodoreroosevelt","winstonchurchill","mahatmagandhi","martinlutherking","nelsonmandela","maozetung","josephstalin","adolfhitler","mussolini","charlesdeGaulle","sigmundfreud","karlmarx","charlesdarwin","alberteinstein"] },

  // Common misspellings (correct versions)
  { id:48, name:"Tricky Words",          emoji:"✅", wpmTarget:48,  accuracy:75, color:"#4ade80", words:["accommodate","achieve","acknowledge","aggressive","apparent","appearance","argument","beautiful","beginning","believe","calendar","caribbean","cemetery","committee","conscience","conscientious","definitely","disappear","embarrass","environment","exhilarate","fluorescent","foreign","grateful","guarantee","harass","height","immediately","independent","indispensable","liaison","lightning","maintenance","maneuver","mischievous","necessary","noticeable","occasion","occurrence","parallel","pastime","perseverance","precede","privilege","pronunciation","publicly","questionnaire","receive","recommend","referred","relevant","restaurant","rhyme","rhythm","separate","sergeant","succeed","supersede","surprise","technique","threshold","tomorrow","twelfth","vacuum","vague","vengeance","weird","whether","withhold","yacht"] },

  // Keyboard row practice mixed
  { id:49, name:"Keyboard Rows",         emoji:"⌨️", wpmTarget:58,  accuracy:75, color:"#818cf8", words:["queuepop","quizwerp","quixote","pewpewpew","typewriter","proprietor","rupture","poetry","powertower","query","equip","queue","perpetuity","quarterly","quipster","perturb","prettier","preppier","quieter","portrayer","asdfghjkl","flashsalad","galahad","halfhalf","gladhand","lashfall","halfshaft","salsa","flag","gash","flask","slash","zxcvbnm","zinc","maxim","venom","combo","numb","bomb","comb","zap","buzz","fizz","jazz","fuzz"] },

  // One hand words (left hand QWERTY)
  { id:50, name:"Left Side",             emoji:"🤚", wpmTarget:35,  accuracy:75, color:"#f87171", words:["bags","dagger","edge","egg","fad","grave","grace","decreased","brace","caged","staged","debate","great","based","greed","breed","beast","feast","grease","steel","taste","after","safer","refer","effect","stead","water","trade","swear","aware","stare","brave","grave","waste","grade","rated","grate","crate","adverb","crave","beard","create","berate","debate","exert","extra","feast","grace","graze","restate","starve","stave","sweet","treat","tread","wrest"] },

  // Right hand words (QWERTY)
  { id:51, name:"Right Side",            emoji:"🖐️", wpmTarget:35,  accuracy:75, color:"#fb923c", words:["million","union","opinion","onion","noon","moon","numb","holm","hull","hill","him","hip","hit","inn","nil","oil","ohm","him","ink","inn","ion","jolly","join","kiln","kill","loin","look","loop","lull","lumpy","milk","mill","mini","monk","moon","moil","moll","noun","null","numb","ohm","oink","only","onion","opium","pull","poll","polo","poky","polo","pool","pony","puny","pylon","junk","link","lion","limp","limp","linn","lip"] },

  // Speed sentences (no spaces)
  { id:52, name:"Full Sentences",        emoji:"🏁", wpmTarget:60,  accuracy:75, color:"#ef4444", words:["themanranfast","shedranintothehouse","theyatebreakfasttogether","wecantypereallyfastnow","shelovestotypeallday","thekeyboardneverrests","fingersflowlikewaterwhenfast","typingfastereverysinglesession","accuracyfirstspeedsecond","buildthemuscleofthemind","neverletgoofthekeys","keepyourfingersmoving","returnhomealways","breatheandtype","flowlikewater","thinkbeforeyoutype","eyesonthescreen","wristsstayrelaxed","shouldersdown","standtalltype"] },

  // Philosophical quotes
  { id:53, name:"Philosophy",            emoji:"🧠", wpmTarget:58,  accuracy:75, color:"#a78bfa", words:["iknowthatiknownothing","weareallmadehereinaliceinwonderland","hellisotherpeoplesartre","godisdeadnietzsche","thecaveisourmindsplato","maniscondemnedtobefreeexistentialism","toliveiswhatmostpeopleneverdo","theunexaminedlifeisnotworth","manisthemeasureofallthings","cogitoegosum","theloveofmoneyistherootofallevil","allisvanityqohelet","knowledgeispowerfrancisbacon","idescartesergosum","timewaitstfornoone","beautyisintheeyeofthebeholder","thetruthwillsetyoufree","whatdoesitprofitaman"] },

  // Keyboard shortcuts (words)
  { id:54, name:"Shortcut Words",        emoji:"⌨️", wpmTarget:55,  accuracy:75, color:"#38bdf8", words:["control","command","option","shift","alt","delete","backspace","escape","enter","return","tab","capslock","pageup","pagedown","home","end","insert","function","print","scroll","pause","numlock","select","all","copy","paste","cut","undo","redo","save","open","close","quit","find","replace","bold","italic","underline","zoom","minimize","maximize","screenshot","spotlight","refresh","reload","newwindow","newtab","closetab","switchtab","history","bookmark","fullscreen","sidebar"] },

  // World languages words
  { id:55, name:"World Languages",       emoji:"🗣️", wpmTarget:50,  accuracy:75, color:"#e879f9", words:["bonjour","merci","baguette","croissant","cafe","rendezvous","entrepreneur","ballet","genre","naive","hola","gracias","tortilla","siesta","fiesta","mañana","ciao","pasta","pizza","espresso","cappuccino","gelato","aria","crescendo","andante","danke","gesundheit","kindergarten","hamburger","angst","wanderlust","zeitgeist","schadenfreude","karate","karaoke","origami","tsunami","typhoon","tofu","kimchi","bibimbap","ramen","sake","ninja","samurai","anime","manga"] },

  // Running words (long continuous phrases)
  { id:56, name:"Long Phrases",          emoji:"🎯", wpmTarget:62,  accuracy:75, color:"#f43f5e", words:["thefastesttypistsneverlookdown","buildingspeedtakesdailycommitment","everykeystrokebringsyoucloser","thegoalisnotperfectionbutprogress","onehourofpracticetranslatestolifetimeskills","focusonthepresentstrokenottheprevious","letyourfingersleadyourmind","typingislikeswimmingyoujustdoit","muscmemorymakesmastershappen","thesecretisrelentlessdailypractice","speedcomesafteraccuracy","neverrushtheprocess","enjoythejourney","celebratesmallwins","trackingprogressmotivates"] },

  // Difficult consonant clusters
  { id:57, name:"Hard Clusters",         emoji:"🔷", wpmTarget:58,  accuracy:75, color:"#94a3b8", words:["strength","lengths","twelfths","scratched","stretched","scrunched","squelched","twitched","crunched","clenched","blanched","branched","breached","britches","clenches","crunches","squelches","stretches","twitches","wrenches","trenches","benches","bleaches","branches","breeches","breaches","clutches","crutches","drenches","flinches","fretches","inches","latches","lunches","matches","notches","patches","peaches","reaches","retches","sketches","sketched","snatches","speeches","stitches","swatches","switches","teaches","touches","watches","witches","wretches"] },

  // Two-letter starts
  { id:58, name:"Common Words",          emoji:"📝", wpmTarget:60,  accuracy:75, color:"#22c55e", words:["abstract","actually","address","advance","against","already","although","another","because","between","business","careful","certain","chapter","collect","company","complete","computer","contain","control","correct","country","covered","created","culture","decided","develop","different","directly","discover","display","distance","division","during","earlier","eastern","economic","either","element","energy","enough","entire","exactly","example","explain","extend","failure","finally","follow","foreign","forward","freedom","general","getting","government","greater","growth","happen","having","history","however","human","hundred","important","increase","indeed","industry","instead","interest","involve","issues","itself","kingdom","knowing","largely","letter","likely","limited","listen","living","looking","machine","making","market","matter","medium","method","modern","moment","moving","national","nature","needed","neither","network","never","normal","notice","number","object","obtain","occur","offer","often","once","opinion","outside","overall","paper","passed","people","perhaps","period","person","physical","please","point","policy","political","position","possible","power","practice","prepare","present","previous","primary","private","process","produce","program","provide","public","purpose","quality","question","quickly","rather","reason","recent","record","remain","report","require","result","return","review","right","since","social","society","source","special","standard","start","state","still","structure","study","subject","success","suggest","support","system","taken","technology","theory","though","thought","thousand","through","today","together","toward","travel","treatment","tried","truly","understand","united","until","usually","various","version","view","water","whether","while","whole","within","without","world","would","write"] },

  // Emotional words
  { id:59, name:"Emotion Words",         emoji:"💙", wpmTarget:50,  accuracy:75, color:"#fb7185", words:["happiness","sadness","excitement","disappointment","frustration","gratitude","loneliness","anxiety","contentment","enthusiasm","melancholy","nostalgia","serenity","compassion","empathy","jealousy","resentment","forgiveness","acceptance","belonging","vulnerability","resilience","courage","confidence","humility","patience","generosity","kindness","love","joy","peace","hope","faith","trust","honesty","integrity","loyalty","dedication","perseverance","ambition","passion","curiosity","wonder","awe","delight","bliss","euphoria","tranquility","harmony","balance"] },

  // Very long words
  { id:60, name:"Very Long Words",       emoji:"📏", wpmTarget:55,  accuracy:75, color:"#c084fc", words:["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pseudopseudohypoparathyroidism","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia","incomprehensibilities","honorificabilitudinitatibus","thyroparathyroidectomized","dichlorodiphenyltrichloroethane","electroencephalographically","psychoneuroimmunological","spectrophotometrically","radioimmunoelectrophoresis","microspectrophotometries","immunoelectrophoretically","philosophicotheological","counterrevolutionaries","disproportionableness","indistinguishableness"] },

  // Common 3-letter words speed drill
  { id:61, name:"Short Word Rush",       emoji:"⚡",  wpmTarget:65,  accuracy:75, color:"#facc15", words:["the","and","for","are","but","not","you","all","can","her","was","one","our","out","day","get","has","him","his","how","man","new","now","old","see","two","way","who","boy","did","its","let","put","say","she","too","use","dad","any","big","end","far","few","got","had","may","run","set","sit","six","ten","try","win","yet","age","ago","aid","aim","air","ask","bad","bag","bit","buy","car","cut","die","dog","dry","due","ear","eat","eye","far","fly","fun","gas","god","gun","gut","hit","hot","ice","job","key","kid","law","lay","leg","lie","lot","low","map","mix","net","oil","own","pay","per","pit","pot","raw","red","row","rub","shy","sin","sky","tip","top","war","web","wet","win","yes","zip"] },

  // Maximum speed - alternating finger patterns
  { id:62, name:"Fast Patterns",         emoji:"🌊", wpmTarget:70,  accuracy:75, color:"#fbbf24", words:["enenene","ananan","tototo","dididid","laLala","mememe","nanana","sisisi","tetete","vovovo","wiwiwi","pepepep","kekekek","rararar","bububub","cococo","dedede","fififi","gogogo","hahaha","icicic","jojojo","kukuku","lelele","mimimi","nonono","opopop","pupupu","qiqi","rerere","sososo","tutututu","ududud","veveve","wuwuwu","xyxy","yoyoyo","zazaza","ababab","acacac","adadad","aeaeae","afafaf","agagag","ahah","aiaiai","ajaJaj","akakak","alalal","amama","ananан"] },

  // Code snippets (no syntax, just words)
  { id:63, name:"Dev Commands",          emoji:"💾",  wpmTarget:68,  accuracy:75, color:"#4ade80", words:["gitcommit","gitpush","gitpull","gitclone","gitstatus","gitbranch","gitmerge","gitrebase","gitcheckout","npminstall","npmrun","npmbuild","npxcreate","yarninstall","yarnbuild","yarnstart","pipinstall","pythonrun","noderun","cargorun","makefile","dockerfile","kubernetes","kubectl","helminstall","dockerbuild","dockerpush","dockerpull","dockerrun","dockercompose","awscloud","gcpcloud","azurecloud","terraformapply","terraformdestroy","ansibleplaybook","jenkinsbuild","githubactions","circleci","travisci"] },

  // Ultimate challenge - long famous quotes
  { id:64, name:"Long Quotes",           emoji:"📖", wpmTarget:75,  accuracy:75, color:"#f43f5e", words:["itisnotenoughtohaveagoodmindthemainistouseitwell","thegreatesttrickthedevileverDpulledwasconvincinghewasntreal","withgreatpowercomesgreatresponsibility","iamnotafailureifidontsuccessieamafailureonlyifigiveup","theultimatemeasureofamanisnotwherehestands","themostcommonwayPeoplgiveuptheirpowerisbyThinkingtheydontHaveany","wemustallsufferoneoftwoThingspainOfDisciplineorThepainOfregret","thebravemenaredefinednotbyTheirabilitytowinbuTtheircapacitytopersist","youCannotfindpeacebyavoidinglifeyoumustliveit","todayisalwaystheBeginningofthenextpart"] },

  // The Final Boss
  { id:65, name:"Grand Master",          emoji:"👑", wpmTarget:80,  accuracy:75, color:"#dc2626", words:["thequickbrownfoxjumpsoverthelazydog","packMyboxwithFiveDozenliquorjugs","howvexinglyquickdaftzebrasjump","thefiVeboxingwizardsjumPquickly","sphinxofblackquartzjudgeMyvow","fivequackingzephyrsjoltedmywaxbed","Blowzygumsjudgemyphiloxyvat","cwmfjordBankglyphs Vex quiz","jockyvwzsgumphdlFiXqrt","grypHfonwdjumpsVexquiz","waltzBadnymphForquixoticjigs","HeavenlyZephyrsquicklyVexjumP","Vexingfuzzyquackpotjumbled","Brownjugscramquick","Packfiveboxeswith","QUickJumpingfoxes","GlyphsquizzingVex","Waltzjumpsquick","Sphinx Judges vow","Blackquartzjudge"] },

  // ── LEVELS 66-165 ──────────────────────────────────────────────────────────
  { id:66,  name:"Word Flow",          emoji:"🌊", wpmTarget:0, accuracy:75, color:"#06b6d4", words:["although","because","between","children","country","decided","develop","directly","discover","display","distance","division","economic","element","energy","enough","entire","exactly","example","explain"] },
  { id:67,  name:"Smooth Operator",    emoji:"🎷", wpmTarget:0, accuracy:75, color:"#8b5cf6", words:["failure","finally","follow","foreign","forward","freedom","general","getting","government","greater","growth","happen","having","history","however","hundred","important","increase","indeed","industry"] },
  { id:68,  name:"Key Climber",        emoji:"🧗", wpmTarget:0, accuracy:75, color:"#10b981", words:["instead","interest","involve","issues","itself","knowing","largely","letter","likely","limited","listen","living","looking","machine","making","market","matter","medium","method","modern"] },
  { id:69,  name:"Word Weaver",        emoji:"🧵", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["moment","moving","national","nature","needed","neither","network","normal","notice","number","object","obtain","occur","offer","often","opinion","outside","overall","paper","passed"] },
  { id:70,  name:"Steady Stream",      emoji:"💧", wpmTarget:0, accuracy:75, color:"#3b82f6", words:["perhaps","period","person","physical","policy","political","position","possible","power","practice","prepare","present","previous","primary","private","process","produce","program","provide","purpose"] },
  { id:71,  name:"Rapid Rush",         emoji:"⚡", wpmTarget:0, accuracy:75, color:"#facc15", words:["quality","question","quickly","rather","reason","recent","record","remain","report","require","result","return","review","since","social","society","source","special","standard","start"] },
  { id:72,  name:"Precision Peak",     emoji:"🎯", wpmTarget:0, accuracy:75, color:"#ef4444", words:["state","still","structure","study","subject","success","suggest","support","system","taken","theory","though","thought","thousand","through","today","together","toward","travel","treatment"] },
  { id:73,  name:"Focus Fire",         emoji:"🔥", wpmTarget:0, accuracy:75, color:"#f97316", words:["tried","truly","understand","united","until","usually","various","version","view","whether","while","whole","within","without","world","would","write","young","above","across"] },
  { id:74,  name:"Type Storm",         emoji:"🌪️", wpmTarget:0, accuracy:75, color:"#a855f7", words:["action","activity","actual","addition","admit","adopted","advance","advantage","afraid","agency","agreement","ahead","aircraft","allowed","almost","already","also","although","amount","analysis"] },
  { id:75,  name:"Word Blitz",         emoji:"💥", wpmTarget:0, accuracy:75, color:"#ec4899", words:["ancient","animal","announced","another","anyway","apartment","apparently","appeal","applied","approach","appropriate","area","argue","army","around","article","artist","asked","attempt","attention"] },
  { id:76,  name:"Long Haul",          emoji:"🚛", wpmTarget:0, accuracy:75, color:"#34d399", words:["automobile","bibliography","catastrophe","choreography","collaboration","commissioner","commonwealth","comprehensive","congratulations","constitution","contradiction","controversial","conventional","cooperation","corporation","correspondence","deterioration","disappointment","discrimination","disorganization"] },
  { id:77,  name:"Big Words",          emoji:"📚", wpmTarget:0, accuracy:75, color:"#60a5fa", words:["documentation","electromagnetic","embarrassment","encouragement","entertainment","establishment","exaggeration","examination","expenditure","explanation","extraordinary","fundamental","generalization","geographical","hospitalization","identification","illustration","imagination","impersonation","implementation"] },
  { id:78,  name:"Mega Vocab",         emoji:"🧠", wpmTarget:0, accuracy:75, color:"#f472b6", words:["inappropriate","incorporation","independence","industrialization","infrastructure","initialization","instrumentation","interpretation","investigation","justification","liberalization","magnification","manipulation","manufacturing","marginalization","maximization","memorization","minimization","mobilization","modernization"] },
  { id:79,  name:"Word Mountain",      emoji:"⛰️", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["multiplication","naturalization","normalization","notification","optimization","organization","orientation","originality","participation","personalization","polarization","popularization","precipitation","prioritization","privatization","professionalism","prohibition","pronunciation","qualification","rationalization"] },
  { id:80,  name:"Vocab Vault",        emoji:"🔐", wpmTarget:0, accuracy:75, color:"#818cf8", words:["realization","recommendation","reconciliation","regularization","reinterpretation","representation","responsibility","revitalization","simplification","specialization","standardization","subordination","summarization","supplementation","transformation","transportation","visualization","globalization","democratization","commercialization"] },
  { id:81,  name:"Lab Notes",          emoji:"🔬", wpmTarget:0, accuracy:75, color:"#38bdf8", words:["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome","combustion","covalent","cytoplasm","dendrite","dielectric","electrode","electrolyte","endoplasmic","enzyme","equilibrium"] },
  { id:82,  name:"Tech Talk",          emoji:"💻", wpmTarget:0, accuracy:75, color:"#4ade80", words:["fibonacci","frequency","germanium","graviton","greenhouse","gyroscope","hemoglobin","hydraulic","hydrogen","hypotenuse","infrared","insulator","integer","interface","ionosphere","isotope","javascript","kilowatt","kinetics","logarithm"] },
  { id:83,  name:"Science Sprint",     emoji:"⚗️", wpmTarget:0, accuracy:75, color:"#fb923c", words:["magnetism","membrane","metabolism","microwave","molecule","momentum","mutation","nanometer","neutron","nitrogen","nucleotide","oscillation","oxidation","particle","peptide","photon","plasma","polymer","potential","protein"] },
  { id:84,  name:"Data Drive",         emoji:"📊", wpmTarget:0, accuracy:75, color:"#c084fc", words:["proton","quantum","radiation","receptor","resistance","resonance","semiconductor","simulation","spectrum","synapse","synthesis","telescope","temperature","thermometer","transistor","ultraviolet","valence","velocity","wavelength","acceleration"] },
  { id:85,  name:"Code Breaker",       emoji:"🔓", wpmTarget:0, accuracy:75, color:"#2dd4bf", words:["biochemistry","bioinformatics","biotechnology","calcification","catalysis","cryptography","cybernetics","cytogenetics","decomposition","deformation","dehydration","electrolysis","fermentation","fluorescence","geochemistry","geophysics","hematology","hydrolysis","immunology","pharmacology"] },
  { id:86,  name:"Phrase Runner",      emoji:"🏃", wpmTarget:0, accuracy:75, color:"#f43f5e", words:["keepyoureyesontheprize","actionsspeaklouderthanwords","thepenismightierthanthesword","dontputallyoureggsinonebasket","everycloudhasasilverlin","betterlatethannever","twobirdsonestone","lookbeforeyouleap","nothingventurednothinggained","fortunefavorsthebrave"] },
  { id:87,  name:"Quote Dash",         emoji:"💬", wpmTarget:0, accuracy:75, color:"#a78bfa", words:["lifeiswhatyoumakeofit","youmissalltheshotsyoudontshoot","dreambigworkhard","stayhungrystayfoolish","doormattoorchestra","makeithappen","believeinyourself","nevergiveuP","hardworkpaysoff","successisajourney"] },
  { id:88,  name:"Sentence Sprint",    emoji:"🗣️", wpmTarget:0, accuracy:75, color:"#fb923c", words:["theearlybirddoesindeedcatchtheworm","asinglestepstillbeginsajourney","knowingisonestepbutdoingisanother","makeithappenshockeveryone","tomorrowisanewday","yesterdayisgone","todayisagiift","thatiswhyitiscalledthepresent"] },
  { id:89,  name:"Flow State",         emoji:"🌀", wpmTarget:0, accuracy:75, color:"#06b6d4", words:["breatheandletgoofwhatyoucannotcontrol","focusonwhatyoucanchange","everystepforwardisastepawayfrom","dothebestyoucanwithwhatyouhave","progressnotperfectionisthegoal","smallstepsbigdreams","keepmovingforward","onestepatime"] },
  { id:90,  name:"Mind Meld",          emoji:"🧘", wpmTarget:0, accuracy:75, color:"#8b5cf6", words:["patientconsistencybeatsimpatientintensity","slowdowntospeedup","themagichappensjustoutsideyourcomfortzone","bethechangeyouwishtosee","startwhereyouareusewhaty ouhave","embracetheprocess","trustyourjourney","buildyourlegacy"] },
  { id:91,  name:"Alpha Blitz",        emoji:"🔤", wpmTarget:0, accuracy:75, color:"#facc15", words:["abacus","abjure","abrupt","absurd","accrue","acquit","actual","adroit","adverb","affect","affirm","afford","afraid","agency","agenda","aghast","agreed","albeit","alcove","alight"] },
  { id:92,  name:"Beta Burst",         emoji:"💫", wpmTarget:0, accuracy:75, color:"#ef4444", words:["ballot","banish","banner","barely","barter","beacon","behalf","bestow","beyond","binary","bitter","blanch","blazon","blight","blotch","blouse","border","borrow","bought","bounce"] },
  { id:93,  name:"Gamma Grind",        emoji:"💪", wpmTarget:0, accuracy:75, color:"#10b981", words:["cancel","candid","canopy","carbon","casing","casual","caught","cavern","census","centric","chalet","charge","chosen","cipher","circle","citrus","clench","clergy","closet","cobalt"] },
  { id:94,  name:"Delta Drive",        emoji:"🔷", wpmTarget:0, accuracy:75, color:"#3b82f6", words:["dacron","damage","danger","dapper","dawdle","deacon","deadly","decant","decree","defeat","defect","define","degree","delete","deluge","demand","deploy","derive","desert","design"] },
  { id:95,  name:"Epsilon Edge",       emoji:"🎯", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["earthy","edging","effect","effort","eighth","either","elapse","eleven","emerge","enable","encase","encode","endure","engage","engulf","enrich","ensure","entire","equals","escape"] },
  { id:96,  name:"Zeta Zone",          emoji:"🌟", wpmTarget:0, accuracy:75, color:"#c084fc", words:["factor","fading","famine","fashion","fasten","fathom","fierce","figure","filter","fiscal","fissure","fitful","flinch","fluent","flutter","forage","forbid","format","fossil","fringe"] },
  { id:97,  name:"Theta Thrust",       emoji:"🚀", wpmTarget:0, accuracy:75, color:"#34d399", words:["gallop","garble","garish","garner","garnet","gasket","gather","gauche","gentle","gifted","girder","goblin","gotten","govern","gravel","grieve","grovel","grudge","guzzle","hamlet"] },
  { id:98,  name:"Iota Impact",        emoji:"⚡", wpmTarget:0, accuracy:75, color:"#f472b6", words:["handle","happen","harbor","harden","hasten","haunch","hearth","hefted","herald","hiccup","hinder","hoarse","hornet","hostile","huddle","humble","hunger","hustle","hybrid","ignite"] },
  { id:99,  name:"Kappa King",         emoji:"👑", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["impede","import","impose","incite","indeed","infect","inform","ingest","inject","insane","inside","insist","insult","intend","invade","invent","invest","invoke","island","isolate"] },
  { id:100, name:"Century Mark",       emoji:"💯", wpmTarget:0, accuracy:75, color:"#ef4444", words:["thequickbrownfoxjumpsoverthelazydog","packMyboxwithfiveDozenliquorjugs","howvexinglyquickdaftzebrasjump","sphinxofblackquartzjudgemyvow","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic","floccinaucinihilipilification","supercalifragilistic"] },
  { id:101, name:"Bonjour!",           emoji:"🇫🇷", wpmTarget:0, accuracy:75, color:"#3b82f6", words:["bonjour","merci","baguette","croissant","fromage","champagne","rendezvous","entrepreneur","silhouette","boulevard","chauffeur","cuisine","ballet","genre","naive","cliche","facade","fiancee","gauche","chic"] },
  { id:102, name:"Hola!",              emoji:"🇪🇸", wpmTarget:0, accuracy:75, color:"#ef4444", words:["hola","gracias","tortilla","siesta","fiesta","embargo","guerrilla","bonanza","cafeteria","patio","plaza","rodeo","sombrero","tango","tornado","vanilla","mosquito","alligator","avocado","chocolate"] },
  { id:103, name:"Ciao!",              emoji:"🇮🇹", wpmTarget:0, accuracy:75, color:"#10b981", words:["ciao","pizza","pasta","espresso","cappuccino","gelato","aria","crescendo","andante","forte","piano","soprano","bravo","casino","grotto","lagoon","malaria","studio","umbrella","volcano"] },
  { id:104, name:"Danke!",             emoji:"🇩🇪", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["danke","kindergarten","hamburger","angst","wanderlust","zeitgeist","schadenfreude","gesundheit","doppelganger","poltergeist","kaput","rucksack","diesel","cobalt","nickel","quartz","pretzel","pumpernickel","sauerkraut","bratwurst"] },
  { id:105, name:"Konnichiwa!",        emoji:"🇯🇵", wpmTarget:0, accuracy:75, color:"#ec4899", words:["karate","karaoke","origami","tsunami","typhoon","tofu","anime","manga","ninja","samurai","sake","sushi","tempura","teriyaki","hibachi","ramen","wasabi","futon","tycoon","emoji"] },
  { id:106, name:"Annyeong!",          emoji:"🇰🇷", wpmTarget:0, accuracy:75, color:"#8b5cf6", words:["kimchi","bibimbap","bulgogi","japchae","doenjang","gochujang","banchan","galbi","samgyeopsal","sundubu","haemul","pajeon","makgeolli","soju","hanbok","taekwondo","hangul","Seoul","Busan","Incheon"] },
  { id:107, name:"Nihao!",             emoji:"🇨🇳", wpmTarget:0, accuracy:75, color:"#f97316", words:["typhoon","algebra","almanac","arsenal","assassin","caliber","cipher","coffee","cotton","crimson","damask","elixir","gauze","hazard","jasmine","lemon","magazine","mask","mattress","cotton"] },
  { id:108, name:"Salam!",             emoji:"🌙",  wpmTarget:0, accuracy:75, color:"#2dd4bf", words:["algebra","algorithm","almanac","arsenal","assassin","caliber","candy","cipher","coffee","cotton","crimson","damask","elixir","gauze","hazard","jasmine","lemon","magazine","mask","mattress"] },
  { id:109, name:"Namaste!",           emoji:"🇮🇳", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["yoga","karma","nirvana","guru","mantra","avatar","jungle","bungalow","shampoo","loot","punch","bandana","calico","cot","dinghy","dungarees","juggernaut","khaki","pajamas","thug"] },
  { id:110, name:"G'day!",             emoji:"🇦🇺", wpmTarget:0, accuracy:75, color:"#84cc16", words:["boomerang","kangaroo","koala","wallaby","wombat","platypus","dingo","didgeridoo","outback","billabong","arvo","barbie","bludger","bonzer","chook","cobber","drongo","footy","galah","reckon"] },
  { id:111, name:"History Makers",     emoji:"🏛️", wpmTarget:0, accuracy:75, color:"#94a3b8", words:["abrahamlincoln","georgewashington","thomasjefferson","benjaminfranklin","alexanderhamilton","theodoreroosevelt","franklindelanoroosevelt","johnfkennedy","martinlutherking","nelsonmandela"] },
  { id:112, name:"Scientists",         emoji:"🔭", wpmTarget:0, accuracy:75, color:"#38bdf8", words:["alberteinstein","isaacnewton","charlesdarwin","mariecurie","galileogalilei","nikolatesla","stephenhawking","richardfeynman","erwinschrodinger","nielsbohr"] },
  { id:113, name:"Artists",            emoji:"🎨", wpmTarget:0, accuracy:75, color:"#f472b6", words:["leonardodavinci","michelangelo","vincentvangogh","pablopicasso","salvadordali","claudemonet","rembrandt","edvardmunch","jacksonpollock","andywarhol"] },
  { id:114, name:"Writers",            emoji:"✍️", wpmTarget:0, accuracy:75, color:"#c084fc", words:["williamshakespeare","janeausten","charlesdickens","marktwain","ernesthemingway","georgeorwell","fyodordostoevsky","levtolstoy","franzkafka","jamesjoyce"] },
  { id:115, name:"Musicians",          emoji:"🎵", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["beethoven","mozart","bachjohannsebastian","chopinfrederic","tchaikovsky","debussyclaude","vivaldiantonio","brahms","handel","schubert"] },
  { id:116, name:"Home Row Hero II",   emoji:"⌨️", wpmTarget:0, accuracy:75, color:"#10b981", words:["asdfasdf","jkljkljkl","asdfjkl","fjdkslal","afjkdsla","jfkdlsaj","salfjdks","ldkfjsla","askdjfla","jsdlakfj","fladksjf","sdlakfjd","lakjdsff","dfjklsad","klasdfjl"] },
  { id:117, name:"Number Words II",    emoji:"🔢", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["twentyone","twentytwo","twentythree","twentyfour","twentyfive","twentysix","twentyseven","twentyeight","twentynine","thirty","thirtyone","thirtytwo","thirtythree","thirtyfour","thirtyfive"] },
  { id:118, name:"Keyboard Row Mix",   emoji:"🎹", wpmTarget:0, accuracy:75, color:"#8b5cf6", words:["qwerty","asdfgh","zxcvbn","poiuyt","lkjhgf","mnbvcx","qazwsx","edcrfv","tgbyhn","qwertyuiop","asdfghjkl","zxcvbnm","poiuytrewq","lkjhgfdsa","mnbvcxz"] },
  { id:119, name:"Alternating Hands",  emoji:"🤝", wpmTarget:0, accuracy:75, color:"#06b6d4", words:["element","problem","visible","formula","bicycle","suspend","neurotic","penalty","stomach","blanket","captain","diagram","edition","fiction","general","hundred","journey","kingdom","laundry","maximum"] },
  { id:120, name:"Pinky Power",        emoji:"🤙", wpmTarget:0, accuracy:75, color:"#ef4444", words:["quiz","aqua","quick","quote","equal","liquid","queue","quest","queen","quiet","quite","quilt","quake","qualm","quaff","quasar","quarry","quarrel","quagmire","quintet"] },
  { id:121, name:"Monster Words",      emoji:"👾", wpmTarget:0, accuracy:75, color:"#a855f7", words:["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia","pseudopseudohypoparathyroidism","incomprehensibilities","honorificabilitudinitatibus","dichlorodiphenyltrichloroethane","electroencephalographically"] },
  { id:122, name:"Mega Phrases",       emoji:"💪", wpmTarget:0, accuracy:75, color:"#f43f5e", words:["itwasthebestoftimesitwastheworstoftimes","asknotwhatyourcountrycandoforyou","tobeornottobethatisthequestion","fourscoreandsevenyearsago","weholdthesetruthstobeselfevident"] },
  { id:123, name:"Speed Sentence",     emoji:"🏎️", wpmTarget:0, accuracy:75, color:"#facc15", words:["thequickbrownfoxjumpsoverthelazyunknowncreature","packingmyboxwithfivedozenliquorjugsandsomecheese","thefiveboxingwizardsjumpquicklyoverthebrownfox","sphinxoftheancientblackquartzjudgesmyvow"] },
  { id:124, name:"Long Quote",         emoji:"📜", wpmTarget:0, accuracy:75, color:"#818cf8", words:["inthebeginningwasthewordandthewordwaswithgodandthewordwasgod","donotgogentleintothatgoodnightrageinagethedyingofthelight","onesmallstepformanonegiantleapformankind"] },
  { id:125, name:"Tongue Tornado",     emoji:"🌪️", wpmTarget:0, accuracy:75, color:"#fb923c", words:["peterpiperpckedapeckofpickledpepperspeterpiperpcked","shesellsseashellsbytheseashoreandtheshellsshesellaretheshells","howmuchwoodwouldawoodchuckchuckifawoodchuckcouldchuckwood","bettyboterboterbutterbutterisbitter"] },
  { id:126, name:"Two Letter Blitz",   emoji:"⚡", wpmTarget:0, accuracy:75, color:"#34d399", words:["if","of","to","in","is","it","be","as","at","so","we","he","by","or","on","do","me","my","up","an","go","no","us","am","hi","ok","ex","ox","ax","id"] },
  { id:127, name:"Four Letter Frenzy", emoji:"💨", wpmTarget:0, accuracy:75, color:"#60a5fa", words:["able","also","area","back","ball","band","base","been","bill","book","both","call","came","card","care","case","city","come","dark","data","days","deal","dear","deep","door","down","draw","drop"] },
  { id:128, name:"Five Letter Fire",   emoji:"🔥", wpmTarget:0, accuracy:75, color:"#f97316", words:["about","above","abuse","actor","adapt","admit","adopt","adult","after","again","agent","agree","ahead","alarm","album","alert","alike","align","alive","alley","allow","along","alter","angel","anger","angle","angry","ankle"] },
  { id:129, name:"Six Letter Storm",   emoji:"⛈️", wpmTarget:0, accuracy:75, color:"#818cf8", words:["absent","absorb","accent","accept","access","accord","accuse","across","action","active","actual","adjust","admire","affect","afford","agency","almost","amount","amused","annual","answer","appeal","appear","around","arrive","artist","aspect"] },
  { id:130, name:"Seven Heaven",       emoji:"7️⃣",  wpmTarget:0, accuracy:75, color:"#fbbf24", words:["ability","absence","achieve","address","advance","against","amazing","ancient","another","anxiety","approve","arrange","attempt","attract","balance","because","beneath","between","belongs","capable","capture","careful","certain","chapter","classic","climate"] },
  { id:131, name:"Epic Sentences",     emoji:"📖", wpmTarget:0, accuracy:75, color:"#a855f7", words:["thequickbrownfoxjumpsoverthelazydog","itwasabrightcoldday","callmeishmael","tobeornottobe","inalandfarfar","weholdthesetruth","fourscoreandseven","onesmallstep","donotgogentle","stagethefinal"] },
  { id:132, name:"Philosophy",         emoji:"🧠", wpmTarget:0, accuracy:75, color:"#38bdf8", words:["thecaveisourmindsplato","godisdeadnietzsche","hellisotherpeoplesartre","existenceprecedesessence","iamcondemnedtobefree","theunexaminedlifeisnotworthliving","iknowthatiknownothing","beautyisintheeyeofthebeholder"] },
  { id:133, name:"Scripture",          emoji:"📿", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["inthebeginningGodcreatedtheheavensandtheearth","forGodsolovedtheworld","iamthewayandthetruth","theLordismyshepherd","forthewagesofsinisdeath","inthebeginningwastheword","blessedare themeek","lovethelordyourgod"] },
  { id:134, name:"Shakespeare",        emoji:"🎭", wpmTarget:0, accuracy:75, color:"#ec4899", words:["tobeornottobethatisthequestion","alltheworldsastagehakespeare","thequalityofmercyisnotstrained","ifmusicbethefoodofloveplayo","whatsinananamerosebyanyothername"] },
  { id:135, name:"US History",         emoji:"🦅", wpmTarget:0, accuracy:75, color:"#3b82f6", words:["fourscoreandsevenyearsagoourforefathers","weholdthesetruthstobeselfevidentthatall","asknotwhatyourcountrycandoforyou","Ihaveadreamthatmyfourchildren","weshallovercomeweshallovercome"] },
  { id:136, name:"Finger Fury",        emoji:"👊", wpmTarget:0, accuracy:75, color:"#ef4444", words:["fjfjfjfjfj","dkdkdkdkdk","slslslslsl","aasdffdsa","jjklllkkj","asdfghjkl","qwertyuio","zxcvbnmzx","poiuytrewq","lkjhgfdsaz","mnbvcxzmnb","qazwsxedcr","rfvtgbyhnuj","fjdkfjdkfjdk","slafslafsla"] },
  { id:137, name:"Code Marathon",      emoji:"🖥️", wpmTarget:0, accuracy:75, color:"#4ade80", words:["functionreturnsundefined","asyncawaitpromise","trycatchfinallydone","useStateuseffect","reactcomponentprops","classextendscomponent","importexportdefault","constletvarscope","arraymapreducefilter","objectkeysvaluesentries"] },
  { id:138, name:"Emoji Words",        emoji:"😎", wpmTarget:0, accuracy:75, color:"#f472b6", words:["rollinglaughingcrying","facewithtearsofJoy","starstruck","thinkingface","explodinghead","hearteyesface","sunglassesface","grimacingface","fearfulface","confoundedface","wearyfacetired","flushedface","astonishedface","anguishedface","perseveringface"] },
  { id:139, name:"Hard Clusters",      emoji:"💎", wpmTarget:0, accuracy:75, color:"#818cf8", words:["strength","lengths","twelfths","scratched","stretched","scrunched","squelched","twitched","crunched","clenched","blanched","branched","breached","clenches","squelches","stretches","twitches","wrenches","trenches","benches"] },
  { id:140, name:"Suffix Surge",       emoji:"🏄", wpmTarget:0, accuracy:75, color:"#06b6d4", words:["thankfulness","gratefulness","mindfulness","hopefulness","usefulness","harmfulness","helpfulness","spitefulness","carelessness","hopelessness","uselessness","harmlessness","motionless","powerless","speechless","breathless","fearless","thoughtless","worthless","restless"] },
  { id:141, name:"Elite Typist",       emoji:"🏆", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["antidisestablishmentarianismisaverylongword","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobiaisreal","floccinaucinihilipilificationmeansworthless"] },
  { id:142, name:"Master Class",       emoji:"🎓", wpmTarget:0, accuracy:75, color:"#a855f7", words:["extraordinarilyphilosophical","incomprehensiblydisproportionate","uncharacteristicallycounterintuitive","psychoneuroimmunologicaltesting","electroencephalographicallyderived","spectrophotometricallymeasured"] },
  { id:143, name:"Word God",           emoji:"👁️", wpmTarget:0, accuracy:75, color:"#f43f5e", words:["itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheageoffoolishness","tobeornottobethatisthequestionwhethertisnoblerinthemind","weholdthesetruthstobeselfevidentthatallmen"] },
  { id:144, name:"Transcendence",      emoji:"✨", wpmTarget:0, accuracy:75, color:"#c084fc", words:["thefastesthumantypistinhistorycouldtype216wordsperminuteconsistently","moderncomputerkeyboardsaredesignedforspeedaccuracyandcomfort","thetypewriterrevolutionizedbusinesscommunicationinthenineteenthcentury"] },
  { id:145, name:"The Summit",         emoji:"⛰️", wpmTarget:0, accuracy:75, color:"#38bdf8", words:["antidisestablishmentarianismisthepoliticalpositionthatopposesdisestablishment","floccinaucinihilipilificationisthenounform","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis"] },
  { id:146, name:"Speed God I",        emoji:"⚡", wpmTarget:0, accuracy:75, color:"#facc15", words:["thethe","andandand","forforfor","youyouyou","runrunrun","hothotho","bigbigbig","newnewnew","oldoldold","seesee","puttputt","saysay","trytry","gotgot","askask"] },
  { id:147, name:"Speed God II",       emoji:"⚡", wpmTarget:0, accuracy:75, color:"#ef4444", words:["waterwater","everyevery","firstfirst","placeplace","yearsyears","youngyoung","greatgreat","threethree","nevernever","worldworld","aboutabout","rightright","couldcould","stillstill","smallsmall"] },
  { id:148, name:"Speed God III",      emoji:"⚡", wpmTarget:0, accuracy:75, color:"#f97316", words:["practiceaccuracy","improvespeed","buildhabits","focusflow","typefast","neverleave","homerowalways","rhythmkeys","combostreak","fingermuscle","wristrelax","shouldersdown","eyesscreen","breathetype","flowwater"] },
  { id:149, name:"Speed God IV",       emoji:"⚡", wpmTarget:0, accuracy:75, color:"#a855f7", words:["development","environment","technology","information","understanding","experience","important","following","sometimes","something","everything","different","communication","international","organization"] },
  { id:150, name:"Speed God V",        emoji:"⚡", wpmTarget:0, accuracy:75, color:"#ec4899", words:["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia","pseudopseudohypoparathyroidism","incomprehensibilities","dichlorodiphenyltrichloroethane","electroencephalographically","psychoneuroimmunological"] },
  { id:151, name:"The Grind",          emoji:"⚙️", wpmTarget:0, accuracy:75, color:"#94a3b8", words:["consistencybeatsintensity","showupeverysingleday","progressoverperfection","embracethegrindeveryday","onehouradaychangesyourlife","nevermisstwodays","buildthesystem","trusttheprocess","compoundeffect","marginalgains"] },
  { id:152, name:"Iron Fingers",       emoji:"🦾", wpmTarget:0, accuracy:75, color:"#6366f1", words:["fjdkfjdkfjdk","slafslafsla","ksdjfksdjf","alskdjalskd","fjaslfjaslfj","dkfsdkfsdkfs","jflajflajfla","sdkfjsdkfjsdk","lfjalfjalfjal","akfjdakfjdak","sfjdlsfjdl","kadfjkadfjka","dlsfadlsfa","fjasldfjasld","kasjdkasjdkas"] },
  { id:153, name:"The Crucible",       emoji:"🔥", wpmTarget:0, accuracy:75, color:"#ef4444", words:["itwasthebestoftimesitwastheworst","tobeornottobe","callmeishmael","inthebeginning","fourscoreandseven","weholdthesetruth","asknotwhat","onesmallstep","donotgogentle","stagethefinal"] },
  { id:154, name:"Apex Predator",      emoji:"🦁", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["extraordinarilyincredible","incomprehensiblybrilliant","uncharacteristicallyperfect","counterproductivelyefficient","simultaneouslymultitasking","acknowledgementreceived","straightforwardlycomplicated","unpredictablyroutine"] },
  { id:155, name:"Finger Lightning",   emoji:"⚡", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["enenenenene","tototototo","lalalalalala","mememememe","nananananana","sisisisisi","tetetete","vovovovo","wiwiwiwi","pepepepep","kekekekek","rararararar","bububububu","cocococococ","dededededede"] },
  { id:156, name:"Legend I",           emoji:"👑", wpmTarget:0, accuracy:75, color:"#fbbf24", words:["thequickbrownfoxjumpsoverthelazydog","packMyboxwithfiveDozenliquorjugs","howvexinglyquickdaftzebrasjump","sphinxofblackquartzjudgemyvow","fivequackingzephyrsjoltedmywaxbed","blowzygumsjudgemyphiloxyvat","cwmfjordBankglyphsvexquiz"] },
  { id:157, name:"Legend II",          emoji:"👑", wpmTarget:0, accuracy:75, color:"#f43f5e", words:["antidisestablishmentarianismfloccinaucinihilipilification","supercalifragilisticexpialidociouspneumonoultramicroscopic","hippopotomonstrosesquippedaliophobiapseudopseudohypo","incomprehensibilitieshonorificabilitudinitatibus"] },
  { id:158, name:"Legend III",         emoji:"👑", wpmTarget:0, accuracy:75, color:"#a855f7", words:["itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomandfoolishness","tobeornottobethatisthequestionwhetheritisnobler","fourscoreandsevenyearsagoourforefathersbroughtforthupon"] },
  { id:159, name:"Legend IV",          emoji:"👑", wpmTarget:0, accuracy:75, color:"#06b6d4", words:["thefastesthumantypistinhistorycouldtype216wordsperminuteconsistently","moderncomputerkeyboardsaredesignedforspeedaccuracyandcomfort","thetypewriterrevolutionizedbusinesscommunicationinthenineteenthcentury"] },
  { id:160, name:"Legend V",           emoji:"👑", wpmTarget:0, accuracy:75, color:"#10b981", words:["practiceisthemotherof allskillsthemorey outypethemoreyouimprove","youdontneedtobeperfectyouneedtobepersistentandconsistent","thekeyboardisaninstrumentandlikeallinstrumentsitmustbepracticed"] },
  { id:161, name:"Legend VI",          emoji:"💀", wpmTarget:0, accuracy:75, color:"#ef4444", words:["antidisestablishmentarianismisthepoliticalpositionthatopposesdisestablishmentofthechurchofengland","floccinaucinihilipilificationisthenounformmeaning toregardorsomethingas worthless"] },
  { id:162, name:"Legend VII",         emoji:"💀", wpmTarget:0, accuracy:75, color:"#8b5cf6", words:["supercalifragilisticexpialidociousevenatthesoundofit somethingquiteatrociouswillalwaysoundprecocious","pneumonoultramicroscopicsilicovolcanoconiosisisthenamegiventoa lungdisease"] },
  { id:163, name:"Legend VIII",        emoji:"💀", wpmTarget:0, accuracy:75, color:"#f59e0b", words:["itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheageoffoolishnessitwastheepochofbelief","tobeornottobethatisthequestionwhethertisnoblerinthemindtosuffertheoutrangeousfortunes"] },
  { id:164, name:"Legend IX",          emoji:"💀", wpmTarget:0, accuracy:75, color:"#c084fc", words:["fourscoreandsevenyearsagoourforefathersbroughtforthuponthiscontinentanewnationconceivedinliberty","weholdthesetruthstobeselfevidentthatallmenarecreatedequalthattheyareendowedbytheirCreatorwithcertainunalienableRights"] },
  { id:165, name:"True Final Boss",    emoji:"☠️", wpmTarget:0, accuracy:75, color:"#dc2626", words:["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheageoffoolishnessitwastheepochofbelief","tobeornottobethatisthequestionwhetheritisnobler inthemindtosuffertheoutrangeousfortunes"] },
];

export const THEMES = [
  { id:'dark',     name:'Dark',        cost:0,    colors:{ bg:"#0a0a0f", card:"#0f0f1a", purple:"#a78bfa", accent:"#34d399", text:"#e0e0ff", border:"#1e1e30", muted:"#6b7280", faint:"#2e2e44", font:"'JetBrains Mono',monospace" }},
  { id:'midnight', name:'Midnight',    cost:50,   colors:{ bg:"#000010", card:"#050520", purple:"#818cf8", accent:"#38bdf8", text:"#c7d2fe", border:"#1e2040", muted:"#64748b", faint:"#1e293b", font:"'JetBrains Mono',monospace" }},
  { id:'forest',   name:'Forest',      cost:50,   colors:{ bg:"#0a120a", card:"#0f1a0f", purple:"#4ade80", accent:"#86efac", text:"#d1fae5", border:"#1a301a", muted:"#6b7c6b", faint:"#14291a", font:"'JetBrains Mono',monospace" }},
  { id:'sunset',   name:'Sunset',      cost:75,   colors:{ bg:"#120a0a", card:"#1a0f0f", purple:"#f97316", accent:"#fbbf24", text:"#fef3c7", border:"#301a1a", muted:"#927272", faint:"#2d1515", font:"'JetBrains Mono',monospace" }},
  { id:'neon',     name:'Neon',        cost:100,  colors:{ bg:"#000000", card:"#050505", purple:"#ff00ff", accent:"#00ffff", text:"#ffffff", border:"#330033", muted:"#888888", faint:"#1a001a", font:"'JetBrains Mono',monospace" }},
  { id:'ocean',    name:'Ocean',       cost:75,   colors:{ bg:"#000a12", card:"#050f1a", purple:"#38bdf8", accent:"#7dd3fc", text:"#e0f2fe", border:"#0c2a3d", muted:"#5b8fad", faint:"#082033", font:"'JetBrains Mono',monospace" }},
  { id:'lavender', name:'Lavender',    cost:75,   colors:{ bg:"#0a0a12", card:"#100f1e", purple:"#c084fc", accent:"#e879f9", text:"#f5f3ff", border:"#2d1f4a", muted:"#8b7aa8", faint:"#1e1535", font:"'JetBrains Mono',monospace" }},
  { id:'coffee',   name:'Coffee',      cost:50,   colors:{ bg:"#120e08", card:"#1a140c", purple:"#d97706", accent:"#fbbf24", text:"#fef9ec", border:"#3d2c14", muted:"#9c8060", faint:"#2c1e0c", font:"'JetBrains Mono',monospace" }},
];

export const TEST_WORDS = ["the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just","him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","us","great","between","need","large","often","hand","high","place","hold","turn","move","play","spell","air","away","animal","house","point","page","letter","mother","answer","found","study","still","learn","plant","cover","food","sun","four","thought","let","keep","children","feet","land","side","without","once","miss","idea","enough","eat","face","watch","far","really","almost","let","above","girl","sometimes","mountain","cut","young","talk","soon","list","song","leave","family"];

export const SKIP_CHALLENGES = {
  1:  ["asdf","jkl","fj","dk","sl","aa","ff","jj","kk","ll","ss","dd","asd","jkl","fdk","slj","dks","laf","jsd","kfl"],
  2:  ["quit","trip","prop","your","tower","query","wrote","power","petty","outer","worry","trout","quote","wiped","tutor","repot","tower","upper","outdo","prior"],
  3:  ["the","big","and","for","hot","map","key","ask","say","put","old","new","see","try","run","own","two","way","how","get"],
  4:  ["water","every","first","place","years","young","great","three","never","world","about","right","could","still","small","found","study","often","those","light"],
  5:  ["people","before","should","between","through","because","without","another","against","thought","looking","children","problem","school","always","around","family","having"],
  6:  ["practice","keyboard","fingers","accuracy","improve","achieve","journey","forward","perfect","balance","channel","chapter","combine","concern","connect","control"],
  7:  ["development","environment","technology","information","understand","experience","important","following","sometimes","something","everything","different"],
  8:  ["communication","international","organization","understanding","professional","relationship","immediately","particularly","responsibility","approximately"],
  9:  ["implementation","administration","circumstances","representative","accomplishment","infrastructure","simultaneously","recommendations","acknowledgment"],
  10: ["thequickbrownfox","shesellsseashells","howmuchwoodcould","packmyboxwithfive","thefiveboxingwizards","jackdawslovemybig","fixingquartz","jumpingquickly"],
  11: ["extraordinary","indistinguishable","miscommunication","uncharacteristically","counterproductive","straightforwardness","unpredictability","incomprehensible"],
  12: ["practiceisthekeytomastery","focusonaccuracybeforespeed","typingisaskillbuiltovertime","keepyoureyesonthescreen","smoothrhythmbeatsbursttyping"],
  13: ["weholdthesetruthstobeselfevident","inthemiddleofeverydifficultyliesopportunity","successisnotfinalfailureisnotfatal"],
  14: ["tobeornottobethatisthequestion","allthatglittersisnotgold","thereisnothingeithergoodorbadbutthinkingmakesitso"],
  15: ["itwasthebestoftimesitwastheworstoftimes","asknotwhatyourcountrycandoforyou","fourscoreandsevenyearsago"],
  16: ["cardiovascular","hypertension","electromagnetic","spectroscopy","thermodynamics","photosynthesis","chromosome","biochemistry","neuroscience"],
  17: ["function","return","const","async","await","promise","callback","closure","prototype","recursion","iteration","algorithm","variable","boolean","undefined"],
  18: ["peterpiperpckedapeckofpickledpeppers","shesellsseashellsbytheseashore","howmuchwoodwouldawoodchuckchuck","sixslipperysnailsslidslowly"],
  19: ["bethechangeyouwishtoSeeintheworld","theonlywaytodomadworkistolovewhatyoudo","imaginationismoreimportantthanknoWledge"],
  20: ["seventeen","fourteen","nineteen","thirteen","thousand","million","billion","hundred","quarter","twelfth","fortieth","sixtieth","seventieth","eightieth"],
  21: ["elephant","rhinoceros","hippopotamus","chimpanzee","orangutan","crocodile","alligator","salamander","chameleon","porcupine","wolverine","armadillo"],
  22: ["Afghanistan","Bangladesh","Kazakhstan","Madagascar","Mozambique","Philippines","Switzerland","Netherlands","Azerbaijan","Kyrgyzstan","Guatemala","Venezuela"],
  23: ["mitochondria","deoxyribonucleic","electromagnetic","spectroscopy","chromatography","electrochemistry","crystallography","nanotechnology","epidemiology"],
  24: ["symphony","crescendo","diminuendo","fortissimo","pianissimo","allegretto","accelerando","ritardando","syncopation","counterpoint","polyphony","arpeggiate"],
  25: ["spaghetti","carbonara","guacamole","quesadilla","enchilada","bruschetta","bolognese","fettuccine","prosciutto","mozzarella","mascarpone","tiramisu"],
  26: ["groundbreaking","overwhelming","uncomfortable","internationally","misrepresentation","straightforward","underestimated","overcomplicating","misunderstanding"],
  27: ["unconstitutional","disenfranchised","counterintuitive","underdeveloped","interconnected","multidimensional","extraordinarily","unenthusiastically","hypersensitivity"],
  28: ["thefastesttypistsneverlookdown","buildingspeedtakesdailycommitment","everykeystrokebringsyoucloser","thegoalisnotperfectionbutprogress"],
  29: ["gitcommit","gitpush","dockerbuild","npminstall","asyncfunction","trycatchfinally","usestatehook","useeffecthook","arrayreduce","objectentries"],
  30: ["callmoishmael","itwasthebestoftimes","itisatruthuniversallyacknowledged","inthebeginningwastheword","stayhungrystayfoolish"],
  31: ["appendicitis","cholecystitis","pancreatitis","gastroenteritis","cardiovascular","hypertension","arrhythmia","tachycardia","angioplasty","electrocardiogram"],
  32: ["quarterback","linebacker","cornerback","defenseman","goalkeeper","midfielder","tournament","championship","qualification","substitution","threepointline"],
  33: ["thunderstorm","precipitation","evaporation","condensation","atmospheric","stratosphere","troposphere","biodiversity","photosynthesis","decomposition","deforestation"],
  34: ["synergy","leverage","paradigm","scalable","disruption","stakeholder","deliverable","milestone","roadmap","iteration","agile","scrum","kanban","retrospective"],
  35: ["Prometheus","Persephone","Hephaestus","Dionysus","Aphrodite","Poseidon","Artemis","Hermes","Odysseus","Achilles","Agamemnon","Patroclus","Penelope"],
  36: ["peterpiperpckedapeckofpickledpeppers","bettyboterboterbutterbutterisbitter","rubberbabybuggybumpers","uniquenewyork","toyboatoyboat","thirtythreethiefs"],
  37: ["extraordinary","indistinguishable","miscommunication","phenomenologically","philosophically","catastrophically","uncharacteristically","counterproductive"],
  38: ["believeinyourself","nevergiveuP","hardworkpaysoff","dreambigworkhardstayhumble","successisajourney","pushingyourlimits","disciplinebeatstalent"],
  39: ["Canberra","Brasilia","Reykjavik","Kathmandu","Montevideo","Tashkent","Ulaanbaatar","Ouagadougou","Antananarivo","Yamoussoukro","Naypyidaw","Dushanbe"],
  40: ["cryptocurrency","blockchain","machinelearning","artificialintelligence","deeplearning","neuralnetwork","virtualization","containerization","microservices","kubernetes"],
  41: ["their","there","they're","your","you're","its","it's","whose","who's","affect","effect","accept","except","principal","principle","stationary","stationery","complement","compliment"],
  42: ["sunflower","moonlight","thunderstorm","butterfly","grasshopper","dragonfly","butterscotch","honeybee","toadstool","nightfall","daybreak","heartbeat","brainwave"],
  43: ["absolutely","accidentally","approximately","carefully","completely","constantly","correctly","deliberately","efficiently","eventually","fortunately","immediately","incredibly"],
  44: ["predetermined","preposterous","prerequisite","premonition","prehistoric","predominant","preliminary","supernatural","superimposed","superconductor","superstitious"],
  45: ["pneumonia","mnemonic","acquiesce","cacophony","egregious","ephemeral","perfidious","sycophant","ubiquitous","verisimilitude","perspicacious","loquacious","magnanimous"],
  46: ["napoleon","cleopatra","charlemagne","genghiskhan","alexanderthegreat","juliuscaesar","leonardodavinci","galileogalilei","isaacnewton","benjaminfranklin","abrahamlincoln"],
  47: ["accommodate","definitely","embarrass","exhilarate","fluorescent","guarantee","maintenance","maneuver","mischievous","necessary","noticeable","occurrence","parallel","perseverance"],
  48: ["thequickbrownfoxjumpsoverthelazydog","packMyboxwithfiveDozenliquorjugs","howvexinglyquickdaftzebrasjump","sphinxofblackquartzjudgemyvow"],
  49: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pseudopseudohypoparathyroidism","pneumonoultramicroscopicsilicovolcanoconiosis"],
  50: ["iknowthatiknownothing","hellisotherpeoplesartre","godisdeadnietzsche","cogitoegosum","theunexaminedlifeisnotworth","knowledgeispowerfrancisbacon","timewaitsfornoone"],
  51: ["thefastesttypistsneverlookdowntheyknowtheirkeyboardbyheart","buildingspeedtakesdailycommitmentandpracticeneverstops","everykeystrokebringsyouclosertobecomingalegendtypist"],
  52: ["itwasthebestoftimesitwastheworstoftimesitwastheageofwisdom","asknotwhatyourcountrycandoforyouaskwhatyoucandoforyourcountry","fourscoreandsevenyearsagoourforefathersbroughtforthuponthiscontinent"],
  53: ["weholdthesetruthstobeselfevidentthatallmenarecreatedequal","tobeornottobethatisthequestionwhethertisnoblerinthemindtosuffer","inthebeginningwasthewordandthewordwaswithgodandthewordwasgod"],
  54: ["themanwhomovesacannotsinglehandledlymovedthemountainbutbegancarryingsmallstones","onesmallstepformanonegiantleapformankind","donotgogentleintothatgoodnightrageinagethedyingofthelight"],
  55: ["pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia","dichlorodiphenyltrichloroethane","electroencephalographically","psychoneuroimmunological","spectrophotometrically","radioimmunoelectrophoresis"],
  56: ["thequickbrownfoxjumpsoverthelazydog","packMyboxwithfiveDozenliquorjugs","howvexinglyquickdaftzebrasjump","sphinxofblackquartzjudgemyvow","fivequackingzephyrsjoltedmywaxbed","blowzygumsjudgemyphiloxyvat","cwmfjordBankglyphsvexquiz"],
  57: ["extraordinarilyincomprehensibleuncharacteristically","counterproductivepseudoscientificunconstitutional","phenomenologicallyandphilosophicallyspeaking","catastrophicallyoverwhelminglydisastrous"],
  58: ["itwasadarkanstormynightwhenthedetectivearrivedatthesceneofthcrime","shecouldhavechosenanypathinlifebutthechoiceshehadmadeledherhere","thekeyboardisnotjustatoolitisthegatewaytoeveryideaeverthought"],
  59: ["loremipsumdolorsitametconsecteturadipiscingelitseddoeiusmodtemporincididuntutlaboreetdolore","thequickbrownfoxjumpsoverthelazyunicornwhilethewindblowsgentlythroughthetrees"],
  60: ["antidisestablishmentarianismisthepoliticalpositionthatopposesdisestablishment","floccinaucinihilipilificationisthehabi tofregardingsomethingas worthless","supercalifragilisticexpialidociousevenatthesoundofit somethingquiteaatrocious"],
  61: ["thefastestrecordedtypingspeedisover200wordsperminuteachievedbyspeciallytrained","practiceandpersistencearetheonlytruepathstomasteringthekeyboardcompletely"],
  62: ["onetwothreefourfivesixseveneightnineteneleventwelvethirteenfourteenfifteensixteenseventeeneighteennineteentwenty","abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"],
  63: ["thebravemendefinednotbytheirabilitytowinsidsbythecapacitytopersistwhenfacedwithobstacles","youcannotfindpeacebyavoidinglifeyoumustliveitthatistheonlywaytoachievetrueserenity"],
  64: ["itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheageoffoolishnessitwastheepochofbeliefit","asknotwhatyourcountrycandoforyouaskwhatyoucandoforyourcountryforthenationdependsontheeffortsofitscitizenry"],
  65: ["pneumonoultramicroscopicsilicovolcanoconiosisantidisestablishmentarianismfloccinaucinihilipilification","supercalifragilisticexpialidociouslyextraordinaryandabsolutelyincomprehensibleinitsentiretywithoutdoubt"],
  66: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  67: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  68: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  69: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  70: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  71: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  72: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  73: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  74: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  75: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  76: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  77: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  78: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  79: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  80: ["although","between","children","decided","develop","discover","display","element","energy","explain"],
  81: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  82: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  83: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  84: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  85: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  86: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  87: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  88: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  89: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  90: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  91: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  92: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  93: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  94: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  95: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  96: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  97: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  98: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  99: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  100: ["automobile","bibliography","catastrophe","collaboration","commissioner","comprehensive","congratulations","constitution","contradiction","conventional"],
  101: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  102: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  103: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  104: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  105: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  106: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  107: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  108: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  109: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  110: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  111: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  112: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  113: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  114: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  115: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  116: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  117: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  118: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  119: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  120: ["adenosine","algorithm","allotrope","antioxidant","asymptote","atmosphere","biosphere","capacitor","centrifuge","chromosome"],
  121: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  122: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  123: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  124: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  125: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  126: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  127: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  128: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  129: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  130: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  131: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  132: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  133: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  134: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  135: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  136: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  137: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  138: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  139: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  140: ["thequickbrownfoxjumpsoverthelazydog","extraordinarily","incomprehensible","antidisestablishmentarianism","pneumonoultramicroscopic"],
  141: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  142: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  143: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  144: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  145: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  146: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  147: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  148: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  149: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  150: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  151: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  152: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  153: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  154: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  155: ["antidisestablishmentarianism","floccinaucinihilipilification","supercalifragilisticexpialidocious","pneumonoultramicroscopicsilicovolcanoconiosis","hippopotomonstrosesquippedaliophobia"],
  156: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  157: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  158: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  159: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  160: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  161: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  162: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  163: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  164: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
  165: ["antidisestablishmentarianismfloccinaucinihilipilificationsupercalifragilisticexpialidociouspneumonoultramicroscopicsilicovolcanoconiosis","itwasthebestoftimesitwastheworstoftimesitwastheageofwisdomitwastheepochofbelief"],
};